// server/lib/movement/foot-speed.js
//
// Speedster S1 — earned foot-speed. Run a lot + raise agility → slowly faster,
// forever, but never runaway. The cap stops being a static table and becomes a
// function of the player's own agility level (movement.sprint skill), so the
// anti-cheat ceiling RISES with progression instead of false-positiving a fast
// runner as a speed-hacker.
//
// The no-runaway shape (industry standard — League/Dota/Elden Ring): no hard cap,
// TWO soft caps with diminishing returns, so the bonus is noticeable early and
// glacial at the top — mathematically never game-breaking. True super-speed is a
// separate costed POWER (S4), not more agility.
//
// Pure math + a guarded skill-level read. All constants are CONCORD_SPRINT_* env
// dials (playtest fodder, not invariants). Behind CONCORD_EARNED_SPEED at the
// call site — off → the legacy static walk cap, byte-identical.

const num = (v, d) => { const n = Number(v); return Number.isFinite(n) ? n : d; };
const dial = (name, def) => num(process.env[name], def);

// Jog floor (the un-skilled on-foot speed the bonus builds on). The legacy
// VEHICLE_MAX_SPEED_MPS.walk (16) stays the ceiling for *un-skilled* movers; a
// skilled runner legitimately grows past it via the function below.
export const BASE_FOOT_SPEED = () => dial("CONCORD_SPRINT_BASE", 6.0);

/**
 * Agility bonus (m/s) at movement.sprint level L — double-soft-capped:
 *   tier 1 (L≤SC1):       full value   R1
 *   tier 2 (SC1<L≤SC2):   soft-capped  R2
 *   tier 3 (L>SC2):       steep cut    R3
 * Tuned: ~+5 m/s by L25 (→11), ~+8.3 by L80 (→14.3), a crawl past that.
 */
export function agilityBonus(level) {
  const L = Math.max(1, num(level, 1));
  const SC1 = dial("CONCORD_SPRINT_SC1", 25);
  const SC2 = dial("CONCORD_SPRINT_SC2", 80);
  const R1 = dial("CONCORD_SPRINT_R1", 0.20);
  const R2 = dial("CONCORD_SPRINT_R2", 0.06);
  const R3 = dial("CONCORD_SPRINT_R3", 0.015);
  const t1 = Math.min(L, SC1) * R1;
  const t2 = Math.max(0, Math.min(L, SC2) - SC1) * R2;
  const t3 = Math.max(0, L - SC2) * R3;
  return t1 + t2 + t3;
}

/** Earned on-foot speed (m/s) at agility level L. Monotonic, concave, no runaway. */
export function footSpeed(level) {
  return Math.round((BASE_FOOT_SPEED() + agilityBonus(level)) * 1000) / 1000;
}

/**
 * The anti-cheat on-foot ceiling for a given agility level — footSpeed × a
 * tolerance band (network jitter / frame batching). Server-authoritative: the
 * caller derives `level` from the server-stored skill, never the client.
 */
export function maxFootSpeedFor(level) {
  const tol = dial("CONCORD_SPRINT_TOLERANCE", 1.15);
  return Math.round(footSpeed(level) * tol * 1000) / 1000;
}

// XP from real running: distance actually sprinted, scaled. (Stamina-gated at the
// emit site so idle/AFK can't farm it.)
export const SPRINT_XP_PER_METER = () => dial("CONCORD_SPRINT_XP_PER_METER", 0.02);

/**
 * Read a user's agility (movement.sprint) level from the skill substrate.
 * Guarded — missing skill / no db → level 1 (= base foot speed). The skill DTU
 * id mirrors skill-progression.recordGameplayXP: `skill_<uid8>_<action>`.
 */
export function agilityLevelFor(db, userId) {
  if (!db || !userId) return 1;
  try {
    const id = `skill_${String(userId).slice(0, 8)}_movement_sprint`;
    const row = db.prepare("SELECT skill_level FROM dtus WHERE id = ?").get(id);
    return row?.skill_level ? Math.max(1, num(row.skill_level, 1)) : 1;
  } catch {
    return 1;
  }
}

/**
 * Award movement.sprint XP for distance actually moved on foot. Mirrors
 * skill-progression.recordGameplayXP's skill-DTU shape so the same row backs
 * agilityLevelFor. Distance-scaled (× SPRINT_XP_PER_METER); the caller gates it
 * on real on-foot movement so idle/AFK can't farm it. Guarded, never throws.
 * @returns {{ok:boolean, level?:number, leveledUp?:boolean}}
 */
export function awardSprintXp(db, userId, meters) {
  if (!db || !userId) return { ok: false };
  const m = num(meters, 0);
  if (m <= 0) return { ok: false, reason: "no_distance" };
  try {
    const id = `skill_${String(userId).slice(0, 8)}_movement_sprint`;
    const row = db.prepare("SELECT skill_level FROM dtus WHERE id = ?").get(id);
    if (!row) {
      db.prepare(`INSERT INTO dtus (id, type, title, creator_id, data, skill_level, created_at, last_used_at)
                  VALUES (?, 'skill', 'Sprint', ?, ?, 1, ?, ?)`)
        .run(id, String(userId), JSON.stringify({ action: "movement_sprint", autoGenerated: true, hidden: true, system: true }),
             Math.floor(Date.now() / 1000), Math.floor(Date.now() / 1000));
    }
    const before = db.prepare("SELECT skill_level FROM dtus WHERE id = ?").get(id)?.skill_level ?? 1;
    const next = Math.round((before + m * SPRINT_XP_PER_METER()) * 1000) / 1000;
    db.prepare("UPDATE dtus SET skill_level = ?, last_used_at = ? WHERE id = ?")
      .run(next, Math.floor(Date.now() / 1000), id);
    return { ok: true, level: next, leveledUp: Math.floor(next) > Math.floor(before) };
  } catch {
    return { ok: false };
  }
}

export default footSpeed;
