// server/scripts/cartographer/render.js
//
// Writers for the human-readable cartographer outputs. Read SYSTEMS.json
// shape (built by cartograph.js) and emit:
//   - SYSTEMS.md    — narrative inventory
//   - GAPS.md       — actionable gap table
//   - NOVEL.md      — Concord-unique substrate
//   - CARTOGRAPH_DRIFT.md            — comment-vs-truth discrepancies
//   - CARTOGRAPH_WIRING_STATUS.md    — auto-doc for human merge into CLAUDE.md
//   - systems-graph.dot              — graphviz source (rendered to .svg
//                                       by the npm script if `dot` is on PATH)
//
// All writers are pure: input report object → string.

import { writeFile } from "node:fs/promises";

export async function renderAll(outDir, report, novelty) {
  await Promise.all([
    writeFile(`${outDir}/SYSTEMS.md`, renderSystemsMd(report), "utf-8"),
    writeFile(`${outDir}/GAPS.md`, renderGapsMd(report), "utf-8"),
    writeFile(`${outDir}/NOVEL.md`, renderNovelMd(report, novelty), "utf-8"),
    writeFile(`${outDir}/CARTOGRAPH_DRIFT.md`, renderDriftMd(report), "utf-8"),
    writeFile(`${outDir}/CARTOGRAPH_WIRING_STATUS.md`, renderWiringStatusMd(report), "utf-8"),
    writeFile(`${outDir}/systems-graph.dot`, renderGraphDot(report), "utf-8"),
  ]);
}

// ── SYSTEMS.md ────────────────────────────────────────────────────────────

export function renderSystemsMd(r) {
  const s = r.stats;
  const lines = [];
  lines.push("# Concord Cognitive Engine — Systems Inventory");
  lines.push("");
  lines.push(`_Auto-generated by cartographer at ${r.generatedAt}. Do not hand-edit; edit categories.js or run wiring._`);
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(`- **Tables**: ${s.tableCount} (${s.deadTableCount} dead)`);
  lines.push(`- **Routes**: ${s.routeCount}`);
  lines.push(`- **Macros**: ${s.macroCount} across ${s.macroDomainCount ?? "?"} domains`);
  lines.push(`- **Heartbeats**: ${s.heartbeatCount}`);
  lines.push(`- **Lenses**: ${s.lensCount} frontend`);
  lines.push(`- **Modules**: ${s.moduleCount} in MODULE_REGISTRY (${s.orphanModuleCount} orphan, ${s.dormantModuleCount} dormant)`);
  lines.push(`- **Universe coverage** (in-scope): ${s.coveragePresent} present / ${s.coverageInScope} total → ${s.coverageInScope ? Math.round(100 * s.coveragePresent / s.coverageInScope) : 0}%`);
  lines.push(`- **Runtime introspect**: ${r.runtime.booted ? `booted in ${r.runtime.bootDurationMs}ms` : `failed (${r.runtime.reason ?? "unknown"})`}`);
  lines.push("");

  // Heartbeats — prefer runtime, fall back to static callsites
  lines.push("## Heartbeats (frequency-sorted)");
  lines.push("");
  lines.push("| ID | Frequency (ticks) | Approx interval |");
  lines.push("|---|---:|---|");
  const hbSource = (r.runtime.heartbeats && r.runtime.heartbeats.length > 0)
    ? r.runtime.heartbeats
    : (r.static?.heartbeatCallsites || []);
  const sortedHb = [...hbSource].sort((a, b) => a.frequency - b.frequency);
  for (const hb of sortedHb) {
    const sec = (hb.frequency * 15);
    const interval = sec < 60 ? `${sec}s` : sec < 3600 ? `${(sec / 60).toFixed(1)}min` : `${(sec / 3600).toFixed(1)}h`;
    lines.push(`| \`${hb.id}\` | ${hb.frequency} | ${interval} |`);
  }
  lines.push("");

  // Macro domains alphabetical — prefer runtime, fall back to static callsites
  lines.push("## Macro Domains (alphabetical)");
  lines.push("");
  const macroSource = (r.runtime.macros && r.runtime.macros.length > 0)
    ? r.runtime.macros
    : (r.static?.macroCallsites || []);
  const byDom = new Map();
  for (const m of macroSource) {
    if (!byDom.has(m.domain)) byDom.set(m.domain, []);
    byDom.get(m.domain).push(m.name);
  }
  const domainKeys = [...byDom.keys()].sort();
  for (const dom of domainKeys) {
    const names = byDom.get(dom).sort();
    lines.push(`- **${dom}** (${names.length}): ${names.map(n => `\`${n}\``).join(", ")}`);
  }
  lines.push("");

  // Coverage by category
  lines.push("## Software-Universe Coverage");
  lines.push("");
  lines.push("| Category | Status | Scope | Target lens | Hits |");
  lines.push("|---|---|---|---|---|");
  for (const c of (r.coverage || []).sort((a, b) => (b.matchedManifests.length + b.matchedRoutes.length) - (a.matchedManifests.length + a.matchedRoutes.length))) {
    const hits = c.matchedManifests.length + c.matchedMacroDomains.length + c.matchedRoutes.length + c.matchedLensDirs.length;
    lines.push(`| \`${c.category}\` | ${badge(c.status)} | ${c.scope} | ${c.proposedTargetLens ?? "-"} | ${hits} |`);
  }
  lines.push("");

  // Lens dirs
  lines.push("## Frontend Lens Directories");
  lines.push("");
  const lensesWith = (r.static?.lensDirs || []).filter(l => l.hasPage).length;
  const lensesWithout = (r.static?.lensDirs || []).filter(l => !l.hasPage).length;
  lines.push(`Total: ${r.static?.lensDirs?.length ?? 0} (${lensesWith} with page.tsx, ${lensesWithout} without)`);
  lines.push("");

  return lines.join("\n");
}

// ── GAPS.md ──────────────────────────────────────────────────────────────

export function renderGapsMd(r) {
  const x = r.crossRef;
  const lines = [];
  lines.push("# Gaps & Wire Targets");
  lines.push("");
  lines.push(`_Generated ${r.generatedAt}. Each gap proposes a concrete wire action._`);
  lines.push("");

  // Dead tables
  lines.push(`## Dead tables (${x.deadTables.length})`);
  lines.push("");
  if (x.deadTables.length === 0) {
    lines.push("_None._");
  } else {
    lines.push("| Table | Migration | Wire option | Archive option |");
    lines.push("|---|---|---|---|");
    for (const d of x.deadTables.slice(0, 100)) {
      lines.push(`| \`${d.name}\` | ${d.migration} | \`analytics.${d.name}Stats\` macro | // REPLACED_BY: migration_NN |`);
    }
    if (x.deadTables.length > 100) lines.push(`| ... | _+${x.deadTables.length - 100} more_ | | |`);
  }
  lines.push("");

  // Orphan modules
  lines.push(`## Orphan modules (${x.orphanModules.length})`);
  lines.push("");
  if (x.orphanModules.length === 0) lines.push("_None._");
  else {
    lines.push("| Module | File | Action |");
    lines.push("|---|---|---|");
    for (const o of x.orphanModules.slice(0, 50)) {
      lines.push(`| \`${o.id}\` | ${o.file ?? "(?)"} | confirm dead → archive, OR import from a wire site |`);
    }
    if (x.orphanModules.length > 50) lines.push(`| ... | _+${x.orphanModules.length - 50} more_ | |`);
  }
  lines.push("");

  // Dormant modules
  lines.push(`## Dormant ghost-fleet / emergent modules (${x.dormantModules.length})`);
  lines.push("");
  if (x.dormantModules.length === 0) lines.push("_None — every module either has a heartbeat or is invoked by a macro callsite._");
  else {
    lines.push("| Module | Subsystem | importedBy | Wire shape |");
    lines.push("|---|---|---:|---|");
    for (const d of x.dormantModules.slice(0, 50)) {
      lines.push(`| \`${d.id}\` | ${d.subsystem ?? "-"} | ${d.importedBy ?? 0} | add heartbeat OR macro registration |`);
    }
    if (x.dormantModules.length > 50) lines.push(`| ... | _+${x.dormantModules.length - 50} more_ | | |`);
  }
  lines.push("");

  // Headless backends
  lines.push(`## Headless backend domains (${x.headlessBackends.length})`);
  lines.push("");
  if (x.headlessBackends.length === 0) lines.push("_None — every macro domain has a matching frontend lens dir._");
  else {
    lines.push("| Domain | Macro count | Suggested frontend lens dir |");
    lines.push("|---|---:|---|");
    for (const h of x.headlessBackends.slice(0, 50)) {
      lines.push(`| \`${h.domain}\` | ${h.macroCount} | \`concord-frontend/app/lenses/${h.domain.replace(/_/g, "-")}/page.tsx\` |`);
    }
  }
  lines.push("");

  // Orphan lenses
  lines.push(`## Orphan lenses (${x.orphanLenses.length})`);
  lines.push("");
  if (x.orphanLenses.length === 0) lines.push("_None._");
  else {
    lines.push("| Lens dir | Reason | Action |");
    lines.push("|---|---|---|");
    for (const o of x.orphanLenses.slice(0, 50)) {
      lines.push(`| \`${o.frontendDir}\` | ${o.reason} | wire backend OR remove |`);
    }
    if (x.orphanLenses.length > 50) lines.push(`| ... | _+${x.orphanLenses.length - 50} more_ | |`);
  }
  lines.push("");

  // Unused macros (top sample only — chat router invokes dynamically, expect over-reports)
  lines.push(`## Unused macros (${x.unusedMacros.length})`);
  lines.push("");
  lines.push("> Heuristic — chat router invokes macros dynamically by name, so over-reports are expected. Cross-referenced against `publicReadDomains` allowlist.");
  lines.push("");
  if (x.unusedMacros.length === 0) lines.push("_None._");
  else {
    lines.push("| Domain | Macro |");
    lines.push("|---|---|");
    for (const u of x.unusedMacros.slice(0, 30)) {
      lines.push(`| \`${u.domain}\` | \`${u.name}\` |`);
    }
    if (x.unusedMacros.length > 30) lines.push(`| ... | _+${x.unusedMacros.length - 30} more_ |`);
  }
  lines.push("");

  // Unshaped events
  lines.push(`## Unshaped socket events (${x.unshapedEvents.length})`);
  lines.push("");
  if (x.unshapedEvents.length === 0) lines.push("_None — every emit is registered in `event-shapes.js`._");
  else {
    lines.push("| Event | First emitter | Action |");
    lines.push("|---|---|---|");
    for (const e of x.unshapedEvents.slice(0, 50)) {
      lines.push(`| \`${e.event}\` | ${e.emitterFile}:${e.emitterLine} | add to event-shapes.js |`);
    }
  }
  lines.push("");

  // Universe coverage gaps
  lines.push("## Universe-coverage gaps (in-scope categories)");
  lines.push("");
  lines.push("| # | Category | Status | Target lens |");
  lines.push("|---:|---|---|---|");
  const inScope = (r.coverage || []).filter(c => c.scope === "in" && c.status !== "present").sort((a, b) => (a.priority ?? 999) - (b.priority ?? 999));
  for (const c of inScope) {
    const pri = c.priority != null ? `**${c.priority}**` : "-";
    lines.push(`| ${pri} | \`${c.category}\` | ${badge(c.status)} | ${c.proposedTargetLens ?? "-"} |`);
  }
  lines.push("");

  return lines.join("\n");
}

// ── NOVEL.md ─────────────────────────────────────────────────────────────

export function renderNovelMd(r, novelty) {
  const lines = [];
  lines.push("# Concord-Unique Inventions");
  lines.push("");
  lines.push("_Auto-seeded by cartographer; hand-curate after each pass. Each entry documents a substrate primitive that doesn't exist elsewhere or that Concord composes in a distinctive way._");
  lines.push("");
  lines.push(`Generated ${r.generatedAt}. Source: \`server/scripts/cartographer/novelty-tags.js\`.`);
  lines.push("");
  for (const n of novelty || []) {
    lines.push(`## ${n.title}`);
    lines.push("");
    lines.push(`- **Source**: \`${n.file}\``);
    lines.push(`- **Novelty tag**: ${n.tag}`);
    lines.push(`- **What's novel**: ${n.reason}`);
    lines.push("");
  }
  return lines.join("\n");
}

// ── CARTOGRAPH_DRIFT.md ──────────────────────────────────────────────────

export function renderDriftMd(r) {
  const drift = r.drift ?? [];
  const lines = [];
  lines.push("# Cartographer Drift Report");
  lines.push("");
  lines.push("_Comment-vs-truth discrepancies in the codebase. Each entry pairs a comment with the actual count from cartographer recon._");
  lines.push("");
  lines.push(`Generated ${r.generatedAt}.`);
  lines.push("");
  if (drift.length === 0) {
    lines.push("_No drifts detected at this pass._");
  } else {
    lines.push("| File | Line | Comment claims | Cartographer counts | Δ |");
    lines.push("|---|---:|---|---:|---:|");
    for (const d of drift) {
      lines.push(`| ${d.file} | ${d.line} | ${d.claim} | ${d.actual} | ${d.delta > 0 ? "+" : ""}${d.delta} |`);
    }
  }
  lines.push("");
  return lines.join("\n");
}

// ── CARTOGRAPH_WIRING_STATUS.md ─────────────────────────────────────────

export function renderWiringStatusMd(r) {
  const lines = [];
  lines.push("# Auto-Generated Wiring Status");
  lines.push("");
  lines.push("_Source for the `Current Wiring Status` section in CLAUDE.md. Human merges; cartographer never auto-rewrites CLAUDE.md._");
  lines.push("");
  lines.push(`Generated ${r.generatedAt}.`);
  lines.push("");
  lines.push("## Heartbeat-registered modules");
  lines.push("");
  const hbSrc = (r.runtime.heartbeats && r.runtime.heartbeats.length > 0)
    ? r.runtime.heartbeats
    : (r.static?.heartbeatCallsites || []);
  for (const hb of [...hbSrc].sort((a, b) => a.frequency - b.frequency)) {
    lines.push(`- \`${hb.id}\` (frequency ${hb.frequency}${hb.neverDisable ? ", neverDisable" : ""})`);
  }
  lines.push("");
  lines.push("## Macro domains with macro counts");
  lines.push("");
  const macroSrc = (r.runtime.macros && r.runtime.macros.length > 0)
    ? r.runtime.macros
    : (r.static?.macroCallsites || []);
  const byDom = new Map();
  for (const m of macroSrc) byDom.set(m.domain, (byDom.get(m.domain) ?? 0) + 1);
  for (const [dom, c] of [...byDom.entries()].sort((a, b) => b[1] - a[1])) {
    lines.push(`- \`${dom}\` — ${c} macros`);
  }
  lines.push("");
  lines.push("## Frontend lens count");
  lines.push("");
  lines.push(`- ${r.stats.lensCount} directories under \`concord-frontend/app/lenses/\``);
  lines.push("");
  lines.push("## Orphan / Dormant inventory");
  lines.push("");
  lines.push(`- Orphan modules: ${r.stats.orphanModuleCount}`);
  lines.push(`- Dormant modules: ${r.stats.dormantModuleCount}`);
  lines.push(`- Dead tables: ${r.stats.deadTableCount}`);
  lines.push(`- Headless backends: ${r.crossRef.headlessBackends.length}`);
  lines.push(`- Orphan lenses: ${r.crossRef.orphanLenses.length}`);
  lines.push("");
  return lines.join("\n");
}

// ── systems-graph.dot ────────────────────────────────────────────────────

export function renderGraphDot(r) {
  const lines = [];
  lines.push("digraph Concord {");
  lines.push("  rankdir=LR; node [shape=box, fontname=Helvetica, fontsize=10]; edge [fontsize=8];");
  lines.push("");

  // Nodes: heartbeats (red), macros grouped by domain (blue), lens dirs (green)
  const seen = new Set();
  for (const hb of r.runtime.heartbeats || []) {
    const id = `hb_${safeId(hb.id)}`;
    if (seen.has(id)) continue;
    seen.add(id);
    lines.push(`  ${id} [label="HB ${hb.id}\\nfreq=${hb.frequency}", color=red, style=filled, fillcolor="#ffe0e0"];`);
  }
  const byDom = new Map();
  for (const m of r.runtime.macros || []) byDom.set(m.domain, (byDom.get(m.domain) ?? 0) + 1);
  for (const [dom, c] of byDom.entries()) {
    const id = `dom_${safeId(dom)}`;
    if (seen.has(id)) continue;
    seen.add(id);
    lines.push(`  ${id} [label="${dom}\\n${c} macros", color=blue, style=filled, fillcolor="#e0e0ff"];`);
  }
  for (const lens of (r.static?.lensDirs || []).slice(0, 60)) {
    const id = `lens_${safeId(lens.name)}`;
    if (seen.has(id)) continue;
    seen.add(id);
    lines.push(`  ${id} [label="lens/${lens.name}", color=green, style=filled, fillcolor="#e0ffe0"];`);
  }

  // Edges: lens dir → macro domain when name matches
  for (const lens of (r.static?.lensDirs || []).slice(0, 60)) {
    const lensId = `lens_${safeId(lens.name)}`;
    const candidates = [lens.name, lens.name.replace(/-/g, "_")];
    for (const c of candidates) {
      const domId = `dom_${safeId(c)}`;
      if (seen.has(domId)) {
        lines.push(`  ${lensId} -> ${domId};`);
        break;
      }
    }
  }

  lines.push("}");
  return lines.join("\n");
}

function safeId(s) {
  return String(s).replace(/[^a-zA-Z0-9_]/g, "_");
}

function badge(status) {
  if (status === "present") return "✅ present";
  if (status === "partial") return "🟡 partial";
  return "❌ missing";
}
