// Import-smoke net (issue #1 of the test-foundation plan).
//
// Cheapest, highest-leverage coverage: import EVERY coverage-included module and
// assert it doesn't throw at module-eval time. This catches the most common class
// of breakage for ~2,000 otherwise-untested files — a bad import, a circular dep,
// a top-level crash, a renamed export consumed at module scope — and runs each
// file's top-level code so real coverage climbs out of the ~10% floor.
//
// Ratcheted: files that legitimately can't import under jsdom but aren't in the
// explicit 3D skip list live in `import-smoke-allowlist.json`. A NEW file that
// starts throwing on import fails this test. Regenerate the baseline with:
//   SMOKE_GENERATE=1 npx vitest run tests/smoke/import-smoke.test.tsx
import { describe, it, expect } from 'vitest';
import { readFileSync, writeFileSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { relFromGlobKey, isExcluded, isJsdomIncompatible } from './smoke-files';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ALLOWLIST_PATH = path.join(HERE, 'import-smoke-allowlist.json');

// vite resolves these glob patterns at build time (literals required).
const GLOBS = {
  ...import.meta.glob('../../components/**/*.{ts,tsx}'),
  ...import.meta.glob('../../lib/**/*.{ts,tsx}'),
  ...import.meta.glob('../../hooks/**/*.{ts,tsx}'),
} as Record<string, () => Promise<unknown>>;

interface Target { rel: string; importer: () => Promise<unknown>; }

const all: Target[] = Object.entries(GLOBS)
  .map(([key, importer]) => ({ rel: relFromGlobKey(key), importer }))
  .filter((t) => !isExcluded(t.rel))
  .sort((a, b) => a.rel.localeCompare(b.rel));

const jsdomSkipped = all.filter((t) => isJsdomIncompatible(t.rel));
const candidates = all.filter((t) => !isJsdomIncompatible(t.rel));

function loadAllowlist(): Record<string, string> {
  try {
    return JSON.parse(readFileSync(ALLOWLIST_PATH, 'utf8')).files ?? {};
  } catch {
    return {};
  }
}

async function importEach(targets: Target[]): Promise<Array<{ rel: string; err: string }>> {
  const settled = await Promise.all(
    targets.map(async (t) => {
      try {
        await t.importer();
        return null;
      } catch (e) {
        const err = (e as Error)?.message ?? String(e);
        return { rel: t.rel, err: err.split('\n')[0].slice(0, 220) };
      }
    }),
  );
  return settled.filter((x): x is { rel: string; err: string } => x != null);
}

if (process.env.SMOKE_GENERATE) {
  // Baseline-generation mode: import everything, write the expected-failure set.
  describe('import-smoke [generate baseline]', () => {
    it('writes import-smoke-allowlist.json', async () => {
      const failures = await importEach(candidates);
      const files: Record<string, string> = {};
      for (const f of failures.sort((a, b) => a.rel.localeCompare(b.rel))) files[f.rel] = f.err;
      writeFileSync(
        ALLOWLIST_PATH,
        JSON.stringify(
          {
            _comment:
              'Files that fail to import under jsdom despite not being in the explicit 3D/worker skip list (transitive 3D imports, browser-only deps). Auto-generated by SMOKE_GENERATE=1. A NEW failure outside this set fails import-smoke. Shrink this as files are made importable.',
            files,
          },
          null,
          2,
        ) + '\n',
      );
      console.log(`[smoke] candidates=${candidates.length} jsdom-skipped=${jsdomSkipped.length} baselined-failures=${Object.keys(files).length}`);
      expect(true).toBe(true);
    }, 600_000);
  });
} else {
  const allow = loadAllowlist();
  const toTest = candidates.filter((t) => !(t.rel in allow));

  describe('import-smoke', () => {
    it('every coverage-included module imports without throwing (ratcheted)', async () => {
      const failures = await importEach(toTest);
      if (failures.length) {
        const lines = failures
          .sort((a, b) => a.rel.localeCompare(b.rel))
          .map((f) => `  • ${f.rel}\n      ${f.err}`)
          .join('\n');
        throw new Error(
          `${failures.length} module(s) newly fail to import under jsdom.\n` +
            `Fix the import error, or — only if the file is genuinely browser/3D-only — add it to ` +
            `tests/smoke/import-smoke-allowlist.json (regenerate with SMOKE_GENERATE=1).\n${lines}`,
        );
      }
      expect(failures).toHaveLength(0);
    }, 600_000);

    it('reports the smoke surface (informational)', () => {
      // Not a gate — just visibility into how much of the tree the net covers.
      expect(candidates.length).toBeGreaterThan(0);
      console.log(
        `[smoke] importable=${toTest.length} allowlisted=${Object.keys(allow).length} ` +
          `jsdom-skipped(3D/worker)=${jsdomSkipped.length} of ${all.length} source files`,
      );
    });
  });
}
