/**
 * Example plugin: knowledge-weather-daily
 *
 * Pulls the knowledge-weather + drift-radar views once a day and publishes
 * a single DTU summarizing the state of the system's epistemic atmosphere.
 *
 * Demonstrates:
 *   • macros export — exposes `weather.publish-daily` for ad-hoc invocation
 *   • tick — runs the daily check every heartbeat
 *   • storage — remembers when we last published so we don't double-publish
 *   • dtu creation — uses the sandboxed createDTU helper
 *
 * Deploy: drop this file at server/plugins/installed/example-knowledge-weather/index.js
 * and POST /api/plugins/reload, or restart the server.
 */

export const id = "example.knowledge-weather-daily";
export const name = "Knowledge Weather Daily Summary";
export const version = "1.0.0";
export const description =
  "Publishes a daily DTU summarizing knowledge weather and drift radar.";
export const author = "Concord";
export const license = "MIT";

let _ctx = null;
let _scheduledId = null;

const ONE_DAY_MS = 24 * 60 * 60 * 1000;

export function init(ctx) {
  _ctx = ctx;
  ctx.log("info", "knowledge-weather-daily plugin initialized");
  // Schedule once per day. The scheduler honors plugin lifecycle so cancel
  // is automatic on destroy().
  _scheduledId = ctx.schedule.every(ONE_DAY_MS, () => {
    void publishDaily(ctx);
  });
  return { ok: true };
}

export function destroy() {
  try { _ctx?.schedule.cancel(_scheduledId); } catch { /* ok */ }
  _ctx = null;
  _scheduledId = null;
}

export const macros = {
  // Manual trigger: POST /api/lens/run { domain: "weather", name: "publish-daily" }
  "weather.publish-daily": async (input, ctx) => {
    return publishDaily(ctx ?? _ctx);
  },
};

async function publishDaily(ctx) {
  if (!ctx) return { ok: false, error: "no_context" };

  const lastPublishedAt = ctx.storage.get("lastPublishedAt") ?? 0;
  if (Date.now() - lastPublishedAt < ONE_DAY_MS - 60_000) {
    return { ok: false, reason: "already_published_today" };
  }

  // Use the public intelligence endpoints by calling our own backend via the
  // sandboxed fetch (the loader proxies through the rate-limited LLM/HTTP queue).
  let weather = { fronts: [] };
  let drift = { pairs: [] };
  try {
    const r1 = await fetch("http://localhost:5050/api/intelligence/knowledge-weather");
    weather = await r1.json();
    const r2 = await fetch("http://localhost:5050/api/intelligence/drift-radar");
    drift = await r2.json();
  } catch (e) {
    ctx.log("warn", `intelligence fetch failed: ${e.message}`);
  }

  const date = new Date().toISOString().slice(0, 10);
  const body = formatBody(weather, drift, date);
  const result = await ctx.createDTU({
    title: `Knowledge Weather — ${date}`,
    body,
    domain: "intelligence",
    tags: ["knowledge_weather", "daily_summary", `date:${date}`],
  });

  if (result.ok) {
    ctx.storage.set("lastPublishedAt", Date.now());
    ctx.log("info", `published daily knowledge weather DTU ${result.dtu.id}`);
  } else {
    ctx.log("error", `daily publish failed: ${result.error || "unknown"}`);
  }
  return result;
}

function formatBody(weather, drift, date) {
  const fronts = (weather.fronts || []).slice(0, 6);
  const pairs = (drift.pairs || []).slice(0, 4);

  const frontLines = fronts.map(
    (f) =>
      `  • ${f.domain.padEnd(18)} ${f.status.padEnd(12)} (${
        f.rateChange > 0 ? "+" : ""
      }${(f.rateChange * 100).toFixed(0)}% over prior 24h)`,
  );
  const driftLines = pairs.map(
    (p) =>
      `  • ${p.domainA} ↔ ${p.domainB}  drift=${(p.drift * 100).toFixed(0)}%`,
  );

  return [
    `Knowledge Weather Report — ${date}`,
    ``,
    `## Active fronts`,
    ...frontLines,
    ``,
    `## Drift candidates`,
    ...driftLines,
    ``,
    `(autogenerated by example.knowledge-weather-daily plugin)`,
  ].join("\n");
}
