'use client';

/**
 * SpecDrivenPanel — Code Sprint C #10.
 *
 * GitHub Spec Kit (90k★ in 2 months) made spec-driven development
 * the emerging 2026 standard. We add the substrate with first-class
 * royalty cascade: spec → plan → code, each a citable DTU.
 *
 * Three panes (Copilot Workspace UX):
 *   1. Spec — title + requirements list
 *   2. Plan — milestones generated by spec_to_plan
 *   3. Implementation — runs agent loop via plan_to_code
 */

import { useState, useCallback, useEffect } from 'react';
import { FileCheck, ChevronRight, Sparkles, Loader2, AlertCircle, Globe2, ListChecks, Cpu } from 'lucide-react';
import { api } from '@/lib/api/client';
import { cn } from '@/lib/utils';

interface SpecMeta {
  body?: string;
  requirements?: string[];
  visibility?: string;
}
interface PlanMeta {
  summary?: string;
  milestones?: Array<{ title: string; steps?: string[] }>;
  specDtuId?: string;
}
interface SpecItem { id: string; title: string; created_at: number; meta_json?: string }

async function callMacro<T>(name: string, input: Record<string, unknown>): Promise<T | null> {
  try {
    const r = await api.post('/api/lens/run', { domain: 'code', name, input });
    return (r.data?.result ?? r.data) as T;
  } catch {
    return null;
  }
}

export function SpecDrivenPanel({ projectPath }: { projectPath: string }) {
  const [pane, setPane] = useState<'spec' | 'plan' | 'code'>('spec');
  const [busy, setBusy] = useState<string | null>(null);
  const [err, setErr] = useState<string | null>(null);
  const [ok, setOk] = useState<string | null>(null);

  // Spec pane state
  const [title, setTitle] = useState('');
  const [requirementsText, setRequirementsText] = useState('');
  const [specs, setSpecs] = useState<SpecItem[]>([]);
  const [activeSpecId, setActiveSpecId] = useState<string | null>(null);
  const [activeSpecMeta, setActiveSpecMeta] = useState<SpecMeta | null>(null);

  // Plan pane state
  const [activePlanId, setActivePlanId] = useState<string | null>(null);
  const [activePlanMeta, setActivePlanMeta] = useState<PlanMeta | null>(null);

  // Code pane state
  const [implResult, setImplResult] = useState<{ verdict?: string; iterations?: number; sessionId?: string } | null>(null);

  const refreshSpecs = useCallback(async () => {
    const r = await callMacro<{ ok: boolean; items?: SpecItem[] }>('spec_list', { kind: 'code_spec' });
    if (r?.ok && r.items) setSpecs(r.items);
  }, []);
  useEffect(() => { refreshSpecs(); }, [refreshSpecs]);

  async function createSpec() {
    if (!title.trim() || !requirementsText.trim()) return;
    setBusy('create'); setErr(null); setOk(null);
    const r = await callMacro<{ ok: boolean; specDtuId?: string; reason?: string }>('spec_create', {
      title: title.trim(),
      requirements: requirementsText.split('\n').map((l) => l.trim()).filter(Boolean),
      projectPath,
    });
    if (r?.ok && r.specDtuId) {
      setActiveSpecId(r.specDtuId);
      setActiveSpecMeta({ body: requirementsText, requirements: requirementsText.split('\n').filter(Boolean) });
      setOk(`Spec created: ${r.specDtuId.slice(0, 24)}…`);
      setTitle(''); setRequirementsText('');
      setPane('plan');
      await refreshSpecs();
    } else setErr(r?.reason || 'create failed');
    setBusy(null);
  }

  async function loadSpec(id: string) {
    setActiveSpecId(id);
    setBusy('load'); setErr(null);
    const r = await callMacro<{ ok: boolean; dtu?: { meta?: SpecMeta } }>('spec_get', { id });
    if (r?.ok && r.dtu) setActiveSpecMeta(r.dtu.meta || null);
    setBusy(null);
  }

  async function generatePlan() {
    if (!activeSpecId) return;
    setBusy('plan'); setErr(null); setOk(null);
    const r = await callMacro<{ ok: boolean; planDtuId?: string; summary?: string; milestoneCount?: number; reason?: string }>('spec_to_plan', { specDtuId: activeSpecId });
    if (r?.ok && r.planDtuId) {
      setActivePlanId(r.planDtuId);
      // re-fetch full plan with milestones
      const full = await callMacro<{ ok: boolean; dtu?: { meta?: PlanMeta } }>('spec_get', { id: r.planDtuId });
      if (full?.ok && full.dtu) setActivePlanMeta(full.dtu.meta || null);
      setOk(`Plan: ${r.milestoneCount} milestones`);
      setPane('code');
    } else setErr(r?.reason || 'plan failed');
    setBusy(null);
  }

  async function runImplementation() {
    if (!activePlanId) return;
    setBusy('impl'); setErr(null); setOk(null);
    const r = await callMacro<{ ok: boolean; sessionId?: string; verdict?: string; iterations?: number; reason?: string }>('plan_to_code', {
      planDtuId: activePlanId, projectPath, runner: 'npm', runnerArgs: ['test'],
    });
    if (r?.ok) {
      setImplResult({ verdict: r.verdict, iterations: r.iterations, sessionId: r.sessionId });
      setOk(`Done: ${r.verdict} after ${r.iterations} iter`);
    } else setErr(r?.reason || 'implementation failed');
    setBusy(null);
  }

  return (
    <div className="flex flex-col h-full bg-[#0d1117]">
      <header className="px-3 py-2 border-b border-white/10 flex items-center gap-2">
        <FileCheck className="w-4 h-4 text-fuchsia-400" />
        <span className="text-xs uppercase font-semibold text-gray-300 tracking-wider">Spec-driven</span>
        <span className="ml-auto text-[10px] text-gray-500">{specs.length} spec{specs.length === 1 ? '' : 's'}</span>
      </header>

      {err && <div className="m-2 px-2 py-1 text-[10px] text-red-300 bg-red-500/10 rounded flex items-center gap-1"><AlertCircle className="w-3 h-3" />{err}</div>}
      {ok && <div className="m-2 px-2 py-1 text-[10px] text-emerald-300 bg-emerald-500/10 rounded">{ok}</div>}

      <nav className="px-3 py-1 border-b border-white/10 flex gap-1 text-[10px]">
        {(['spec', 'plan', 'code'] as const).map((p, idx) => (
          <button
            key={p}
            onClick={() => setPane(p)}
            disabled={(p === 'plan' && !activeSpecId) || (p === 'code' && !activePlanId)}
            className={cn(
              'px-2 py-0.5 rounded uppercase tracking-wider flex items-center gap-1',
              pane === p ? 'bg-fuchsia-500/20 text-fuchsia-200' : 'text-gray-500 hover:text-white disabled:opacity-30 disabled:cursor-not-allowed'
            )}
          >
            {idx > 0 && <ChevronRight className="w-2.5 h-2.5" />}
            {p}
          </button>
        ))}
      </nav>

      <div className="flex-1 min-h-0 overflow-y-auto p-3 space-y-3 text-xs">
        {pane === 'spec' && (
          <>
            <div className="space-y-1.5">
              <input
                type="text" value={title} onChange={(e) => setTitle(e.target.value)}
                placeholder="Spec title"
                className="w-full px-2 py-1 text-xs bg-lattice-deep border border-lattice-border rounded text-white"
              />
              <textarea
                value={requirementsText} onChange={(e) => setRequirementsText(e.target.value)}
                placeholder="One requirement per line…"
                rows={6}
                className="w-full px-2 py-1 text-[11px] bg-lattice-deep border border-lattice-border rounded text-white resize-none font-mono"
              />
              <button
                onClick={createSpec} disabled={busy !== null || !title.trim() || !requirementsText.trim()}
                className="text-[10px] px-3 py-1 rounded bg-fuchsia-500 text-white font-bold hover:bg-fuchsia-400 disabled:opacity-50 inline-flex items-center gap-1"
              >
                <Sparkles className="w-3 h-3" /> Create spec
              </button>
            </div>
            <hr className="border-white/10" />
            <div>
              <div className="text-[10px] uppercase tracking-wider text-gray-500 mb-1">Existing specs</div>
              <ul className="space-y-1">
                {specs.map((s) => (
                  <li key={s.id}>
                    <button
                      onClick={() => loadSpec(s.id)}
                      className={cn(
                        'w-full text-left px-2 py-1 rounded text-[11px]',
                        activeSpecId === s.id ? 'bg-fuchsia-500/20 text-fuchsia-200' : 'hover:bg-white/[0.04]'
                      )}
                    >
                      <span className="font-medium">{s.title}</span>
                    </button>
                  </li>
                ))}
              </ul>
            </div>
          </>
        )}

        {pane === 'plan' && (
          <div className="space-y-2">
            {activeSpecMeta?.requirements && (
              <div>
                <div className="text-[10px] uppercase tracking-wider text-gray-500 mb-1">From spec</div>
                <ul className="text-[11px] text-gray-300 space-y-0.5">
                  {activeSpecMeta.requirements.map((r, i) => <li key={i}>• {r}</li>)}
                </ul>
              </div>
            )}
            <button
              onClick={generatePlan} disabled={busy !== null || !activeSpecId}
              className="text-[10px] px-3 py-1 rounded bg-fuchsia-500 text-white font-bold hover:bg-fuchsia-400 disabled:opacity-50 inline-flex items-center gap-1"
            >
              {busy === 'plan' ? <Loader2 className="w-3 h-3 animate-spin" /> : <ListChecks className="w-3 h-3" />}
              Generate plan
            </button>
            {activePlanMeta && (
              <div className="mt-3 space-y-2">
                {activePlanMeta.summary && (
                  <div className="text-[11px] text-gray-300 italic">{activePlanMeta.summary}</div>
                )}
                {(activePlanMeta.milestones || []).map((m, i) => (
                  <div key={i} className="border border-white/10 rounded p-2">
                    <div className="text-[11px] font-bold text-fuchsia-300">{i + 1}. {m.title}</div>
                    {Array.isArray(m.steps) && (
                      <ul className="mt-1 ml-3 text-[10px] text-gray-400 space-y-0.5">
                        {m.steps.map((s, si) => <li key={si}>• {s}</li>)}
                      </ul>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        {pane === 'code' && (
          <div className="space-y-2">
            <button
              onClick={runImplementation} disabled={busy !== null || !activePlanId}
              className="text-[10px] px-3 py-1 rounded bg-fuchsia-500 text-white font-bold hover:bg-fuchsia-400 disabled:opacity-50 inline-flex items-center gap-1"
            >
              {busy === 'impl' ? <Loader2 className="w-3 h-3 animate-spin" /> : <Cpu className="w-3 h-3" />}
              Run plan → code (agent loop)
            </button>
            {implResult && (
              <div className="border border-white/10 rounded p-2 text-[11px]">
                <div>verdict: <span className={cn(implResult.verdict === 'pass' ? 'text-emerald-300' : 'text-amber-300', 'font-bold')}>{implResult.verdict}</span></div>
                <div>iterations: {implResult.iterations}</div>
                <div className="font-mono text-[10px] text-gray-500 mt-1 break-all flex items-center gap-1">
                  <Globe2 className="w-3 h-3" /> {implResult.sessionId}
                </div>
                <div className="text-[10px] text-gray-500 mt-1">
                  Citation chain: spec → plan → session. Original spec author earns from every cited build.
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

export default SpecDrivenPanel;
