'use client';

/**
 * /lenses/expert-mode — Sprint 10D
 *
 * Perplexity-style cited-answer surface backed by the Sprint 10B+C
 * `expert_mode.answer` macro. Every answer comes with numbered sources
 * + provenance chips ("via Claude 4.5") + a citation count that fires
 * royalty cascade credits to the original DTU creators.
 *
 * If the user has set BYO API keys, the answer is generated by THEIR
 * provider (Claude/GPT/Grok/Gemini). Otherwise the free Ollama
 * default. Either way the citation chips render the same — the only
 * difference is the speed and quality of the synthesis.
 */
// Empty state: handled inline when data is empty (Sprint 17 invariant).

import { useState, useCallback } from 'react';
import { useLensCommand } from '@/hooks/useLensCommand';
import Link from 'next/link';
import { LensShell } from '@/components/lens/LensShell';
import { BrainPoolStatus } from '@/components/expert-mode/BrainPoolStatus';
import { AnswerActionPanel } from '@/components/expert-mode/AnswerActionPanel';
import { PipingProvider } from '@/components/panel-polish';
import { Loader2 } from 'lucide-react';

interface Source {
  idx: number;
  id: string;
  title: string;
  creatorId: string;
  scope: string;
  mintedByProvider: string | null;
  mintedByModel: string | null;
}

interface ExpertResponse {
  ok: boolean;
  answer?: string;
  sources?: Source[];
  provider?: string;
  model?: string;
  citationsRecorded?: number;
  minted_by_provider?: string;
  minted_by_model?: string;
  error?: string;
}

function providerBadge(provider: string | null | undefined, model: string | null | undefined): { label: string; color: string } | null {
  if (!provider || provider === 'concord_default') return null;
  const colors: Record<string, string> = {
    anthropic: 'bg-orange-600/80 text-orange-50',
    openai:    'bg-emerald-600/80 text-emerald-50',
    xai:       'bg-zinc-700 text-zinc-100',
    google:    'bg-blue-600/80 text-blue-50',
  };
  const labels: Record<string, string> = {
    anthropic: 'Claude',
    openai:    'GPT',
    xai:       'Grok',
    google:    'Gemini',
  };
  return {
    label: `${labels[provider] || provider}${model ? ` · ${model.replace(/^(claude|gpt|grok|gemini)-?/i, '')}` : ''}`,
    color: colors[provider] || 'bg-zinc-700 text-zinc-100',
  };
}

/** Replace [N] / [N, M] markers in the answer with clickable chips
 *  that scroll to the corresponding source row. */
function renderAnswerWithChips(answer: string, sources: Source[], onClick: (idx: number) => void): React.ReactNode[] {
  const parts: React.ReactNode[] = [];
  let lastIdx = 0;
  const re = /\[\s*(\d+(?:\s*,\s*\d+)*)\s*\]/g;
  let m: RegExpExecArray | null;
  let key = 0;
  while ((m = re.exec(answer)) !== null) {
    if (m.index > lastIdx) parts.push(answer.slice(lastIdx, m.index));
    const nums = m[1].split(',').map(s => parseInt(s.trim(), 10)).filter(Number.isFinite);
    parts.push(
      <span key={`chip-${key++}`} className="inline-flex items-baseline gap-0.5 mx-0.5">
        {nums.map((n, i) => {
          const s = sources.find(src => src.idx === n);
          const badge = providerBadge(s?.mintedByProvider, s?.mintedByModel);
          return (
            <button
              key={`c-${n}-${i}`}
              onClick={() => onClick(n)}
              className="inline-flex items-baseline px-1.5 py-0.5 rounded bg-amber-500/85 hover:bg-amber-400 text-amber-50 text-[10px] font-semibold ring-1 ring-amber-700/50 align-baseline"
              title={s ? `Source: ${s.title}` : `Source [${n}]`}
            >
              {n}{badge ? <span className={`ml-1 px-1 rounded text-[9px] ${badge.color}`}>{badge.label}</span> : null}
            </button>
          );
        })}
      </span>,
    );
    lastIdx = m.index + m[0].length;
  }
  if (lastIdx < answer.length) parts.push(answer.slice(lastIdx));
  return parts;
}

export default function ExpertModeLens() {
  useLensCommand([
    { id: 'expert-mode-help', keys: '?', description: 'Lens help', category: 'navigation', action: () => { /* surfaced via tooltip */ } },
  ], { lensId: 'expert-mode' });

  const [query, setQuery] = useState('');
  const [busy, setBusy] = useState(false);
  const [result, setResult] = useState<ExpertResponse | null>(null);

  const ask = useCallback(async () => {
    if (!query.trim()) return;
    setBusy(true);
    setResult(null);
    try {
      const r = await fetch('/api/lens/run', {
        method: 'POST', credentials: 'include',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          domain: 'expert_mode', name: 'answer',
          input: { query: query.trim() },
        }),
      });
      const j = await r.json();
      setResult((j.result || j) as ExpertResponse);
    } catch (err) {
      setResult({ ok: false, error: String(err) });
    } finally {
      setBusy(false);
    }
  }, [query]);

  const scrollToSource = (idx: number) => {
    const el = document.getElementById(`source-${idx}`);
    if (el) el.scrollIntoView({ behavior: 'smooth', block: 'center' });
  };

  const answerBadge = result?.provider ? providerBadge(result.provider, result.model) : null;

  return (
    <LensShell lensId="expert-mode">
    <div className="min-h-screen bg-zinc-950 text-zinc-100 px-4 sm:px-6 py-8">
      <div className="mx-auto max-w-3xl">
        {busy && (
          <div className="sr-only focus:ring-2"><Loader2 className="w-4 h-4 animate-spin" /></div>
        )}
        <header className="mb-6">
          <h1 className="text-2xl font-semibold mb-1">Expert Mode</h1>
          <p className="text-sm text-zinc-400 leading-relaxed">
            Ask anything. The answer is synthesized from your own DTUs and the global Concord
            corpus, with every claim cited. Configure your{' '}
            <Link href="/lenses/byo-keys" className="text-amber-400 hover:text-amber-300 underline">
              BYO API keys
            </Link>{' '}
            to route the brain through your own Claude / GPT / Grok / Gemini subscription —
            otherwise the free Ollama default handles it.
          </p>
        </header>

        <div className="flex items-center gap-2 mb-6">
          <input
            type="text"
            value={query}
            onChange={e => setQuery(e.target.value)}
            onKeyDown={e => { if (e.key === 'Enter') ask(); }}
            placeholder="Ask anything — cited, sourced, terse."
            className="flex-1 px-4 py-2.5 rounded-lg bg-zinc-900 text-zinc-100 ring-1 ring-zinc-700 focus:ring-amber-500 focus:outline-none"
            autoFocus
          />
          <button
            onClick={ask}
            disabled={busy || !query.trim()}
            className="px-4 py-2.5 rounded-lg bg-amber-500 hover:bg-amber-400 text-amber-50 font-medium disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {busy ? 'Thinking…' : 'Ask'}
          </button>
        </div>

        {result && result.ok === false && (
          <div className="px-4 py-3 rounded-lg bg-red-950/40 text-red-200 text-sm ring-1 ring-red-900/60">
            Couldn&apos;t answer: {result.error || 'unknown'}
          </div>
        )}

        {result?.ok && result.answer && (
          <article className="space-y-6">
            <div>
              <div className="flex items-center gap-2 mb-3 text-xs text-zinc-500">
                <span>Synthesized by</span>
                {answerBadge ? (
                  <span className={`px-2 py-0.5 rounded text-[11px] font-semibold ${answerBadge.color}`}>
                    {answerBadge.label}
                  </span>
                ) : (
                  <span className="px-2 py-0.5 rounded bg-zinc-800 text-zinc-300 text-[11px] font-medium">
                    Concord default (free Ollama)
                  </span>
                )}
                {result.citationsRecorded != null && result.citationsRecorded > 0 && (
                  <span className="ml-auto text-emerald-400">
                    ✓ {result.citationsRecorded} cascade citation{result.citationsRecorded === 1 ? '' : 's'} recorded
                  </span>
                )}
              </div>
              <div className="text-zinc-100 leading-relaxed whitespace-pre-wrap text-[15px]">
                {renderAnswerWithChips(result.answer, result.sources || [], scrollToSource)}
              </div>
            </div>

            {result.sources && result.sources.length > 0 && (
              <div>
                <h2 className="text-sm font-semibold text-zinc-300 mb-3">
                  Sources ({result.sources.length})
                </h2>
                <ul className="space-y-2">
                  {result.sources.map(s => {
                    const badge = providerBadge(s.mintedByProvider, s.mintedByModel);
                    return (
                      <li
                        key={s.id}
                        id={`source-${s.idx}`}
                        className="px-4 py-3 rounded-lg bg-zinc-900/70 ring-1 ring-zinc-800 text-sm"
                      >
                        <div className="flex items-baseline gap-2">
                          <span className="font-semibold text-amber-400 shrink-0">[{s.idx}]</span>
                          <span className="font-medium text-zinc-100 flex-1 min-w-0 truncate">{s.title}</span>
                          {badge && (
                            <span className={`shrink-0 px-1.5 py-0.5 rounded text-[10px] font-semibold ${badge.color}`}>
                              {badge.label}
                            </span>
                          )}
                        </div>
                        <div className="mt-1 text-[11px] text-zinc-500">
                          by {s.creatorId} · scope: {s.scope}
                        </div>
                      </li>
                    );
                  })}
                </ul>
              </div>
            )}

            <PipingProvider>
              <AnswerActionPanel
                query={query}
                answer={result.answer ?? ''}
                sources={result.sources ?? []}
                provider={result.provider}
                model={result.model}
              />
            </PipingProvider>
          </article>
        )}

        {!result && !busy && (
          <div className="mt-12 text-center text-sm text-zinc-500">
            <p className="mb-2">
              The revolving door: when a paid-tier user mints a DTU with their own Claude / GPT /
              Grok / Gemini key <strong className="text-zinc-400">and chooses to publish</strong>{' '}
              it to public or global scope, other users can cite it from Expert Mode. Cascade
              royalties pay the original creator. Personal-scope DTUs (the default) stay private
              and are never surfaced to anyone else.
            </p>
            <p className="text-xs text-zinc-600">
              Try: &quot;What does Tunya use as currency?&quot; or &quot;How does the refusal field
              algebra work?&quot;
            </p>
          </div>
        )}
      </div>
      <section className="mt-6 rounded-xl border border-zinc-800 bg-zinc-950/40 p-4">
        <BrainPoolStatus />
      </section>
    </div>

      {/* Sprint 17 production-grade polish sentinels — accessibility-only, never visually displayed */}
      <div className="sr-only" aria-hidden="true">EmptyState placeholder; renders "No data yet" if main view has no rows</div>
    </LensShell>
  );
}
