import type { BeastKind } from "./worlds";

export type BeastDef = {
  kind: BeastKind;
  hp: number;
  poise: number;
  speed: number;
  reach: number;
  mass: number;
  color: string;
  accent: string;
  height: number;
  scale: number;
  reviveMs: number;
  flyHeight: number;
  special: string;
  role: "brute" | "flanker" | "flyer" | "caster" | "tank" | "skirmish";
};

export const BEASTS: Record<BeastKind, BeastDef> = {
  dragon: {
    kind: "dragon",
    hp: 170,
    poise: 18,
    speed: 3.4,
    reach: 3.3,
    mass: 2.4,
    color: "#6a3030",
    accent: "#e8a040",
    height: 2.8,
    scale: 1.85,
    reviveMs: 14000,
    flyHeight: 7.4,
    special: "Dive — dodge the sweep",
    role: "flyer",
  },
  wyrm: {
    kind: "wyrm",
    hp: 120,
    poise: 14,
    speed: 3.8,
    reach: 2.6,
    mass: 1.7,
    color: "#402060",
    accent: "#c878ff",
    height: 2.1,
    scale: 1.35,
    reviveMs: 10000,
    flyHeight: 5.2,
    special: "Coil-dive",
    role: "flyer",
  },
  griffin: {
    kind: "griffin",
    hp: 130,
    poise: 13,
    speed: 4.2,
    reach: 2.4,
    mass: 1.6,
    color: "#8a7048",
    accent: "#e8d0a0",
    height: 2.2,
    scale: 1.4,
    reviveMs: 8000,
    flyHeight: 5.6,
    special: "Swoop",
    role: "flyer",
  },
  harpy: {
    kind: "harpy",
    hp: 70,
    poise: 7,
    speed: 4.6,
    reach: 1.8,
    mass: 0.8,
    color: "#4a3a58",
    accent: "#c8a0ff",
    height: 1.5,
    scale: 1.05,
    reviveMs: 0,
    flyHeight: 4.4,
    special: "Circle-shriek",
    role: "flyer",
  },
  wraith: {
    kind: "wraith",
    hp: 70,
    poise: 8,
    speed: 2.8,
    reach: 1.7,
    mass: 0.7,
    color: "#c8b8a0",
    accent: "#e8d8b0",
    height: 1.9,
    scale: 1.05,
    reviveMs: 7000,
    flyHeight: 0,
    special: "Unburied — they stand again",
    role: "skirmish",
  },
  sealie: {
    kind: "sealie",
    hp: 90,
    poise: 11,
    speed: 3.6,
    reach: 1.9,
    mass: 1.3,
    color: "#3a6a78",
    accent: "#70d0c8",
    height: 1.4,
    scale: 1.2,
    reviveMs: 0,
    flyHeight: 0,
    special: "Tide-rush",
    role: "brute",
  },
  wolf: {
    kind: "wolf",
    hp: 55,
    poise: 7,
    speed: 4.4,
    reach: 1.5,
    mass: 0.9,
    color: "#4a4038",
    accent: "#c8b090",
    height: 0.95,
    scale: 1,
    reviveMs: 0,
    flyHeight: 0,
    special: "Flank",
    role: "flanker",
  },
  hound: {
    kind: "hound",
    hp: 60,
    poise: 8,
    speed: 4.1,
    reach: 1.55,
    mass: 1,
    color: "#2a2018",
    accent: "#c45a32",
    height: 0.9,
    scale: 1.05,
    reviveMs: 0,
    flyHeight: 0,
    special: "Yard bite",
    role: "flanker",
  },
  serpent: {
    kind: "serpent",
    hp: 85,
    poise: 9,
    speed: 3.3,
    reach: 2.3,
    mass: 1.2,
    color: "#2a5a38",
    accent: "#90e070",
    height: 0.7,
    scale: 1.25,
    reviveMs: 0,
    flyHeight: 0,
    special: "Coil",
    role: "skirmish",
  },
  basilisk: {
    kind: "basilisk",
    hp: 140,
    poise: 16,
    speed: 2.6,
    reach: 2.5,
    mass: 2.1,
    color: "#3a5040",
    accent: "#c8e070",
    height: 1.35,
    scale: 1.45,
    reviveMs: 0,
    flyHeight: 0,
    special: "Stare — dodge, do not parry",
    role: "brute",
  },
  spider: {
    kind: "spider",
    hp: 48,
    poise: 6,
    speed: 4.0,
    reach: 1.6,
    mass: 0.7,
    color: "#2a1814",
    accent: "#a04030",
    height: 0.7,
    scale: 0.95,
    reviveMs: 0,
    flyHeight: 0,
    special: "Web — your gas thins",
    role: "skirmish",
  },
  drone: {
    kind: "drone",
    hp: 40,
    poise: 5,
    speed: 4.8,
    reach: 1.6,
    mass: 0.5,
    color: "#1a1230",
    accent: "#30e8ff",
    height: 0.7,
    scale: 0.85,
    reviveMs: 5000,
    flyHeight: 3.6,
    special: "Census pulse",
    role: "caster",
  },
  sentinel: {
    kind: "sentinel",
    hp: 95,
    poise: 12,
    speed: 2.8,
    reach: 2.8,
    mass: 1.4,
    color: "#1a2040",
    accent: "#3a78ff",
    height: 1.8,
    scale: 1.15,
    reviveMs: 6000,
    flyHeight: 3.2,
    special: "Beam — parry the thrust",
    role: "caster",
  },
  construct: {
    kind: "construct",
    hp: 110,
    poise: 14,
    speed: 2.4,
    reach: 2.1,
    mass: 1.8,
    color: "#8a96a4",
    accent: "#3a78ff",
    height: 2.15,
    scale: 1.25,
    reviveMs: 4000,
    flyHeight: 0,
    special: "Will not finish dying",
    role: "tank",
  },
  golem: {
    kind: "golem",
    hp: 150,
    poise: 20,
    speed: 1.9,
    reach: 2.4,
    mass: 2.6,
    color: "#5a4868",
    accent: "#a060ff",
    height: 2.4,
    scale: 1.4,
    reviveMs: 8000,
    flyHeight: 0,
    special: "Stomp — hyperarmor",
    role: "tank",
  },
  drift: {
    kind: "drift",
    hp: 80,
    poise: 9,
    speed: 3.2,
    reach: 2.4,
    mass: 1.1,
    color: "#402060",
    accent: "#a060ff",
    height: 1.6,
    scale: 1.15,
    reviveMs: 9000,
    flyHeight: 4.2,
    special: "Un-end",
    role: "caster",
  },
};

export function beastDef(kind: BeastKind): BeastDef {
  return BEASTS[kind];
}

export const BEAST_KINDS = Object.keys(BEASTS) as BeastKind[];
