'use client';

/**
 * AgentAutonomyPanel — surfaces Concord's own self-directed goal system.
 *
 * This is a genuinely separate backend cluster from the personal-OKR macros
 * in server/domains/goals.js: 12 macros registered inline in server.js under
 * the "GOAL SYSTEM MACROS" comment block (register("goals", "status"|"list"|
 * "get"|"propose"|"evaluate"|"approve"|"activate"|"progress"|"complete"|
 * "abandon"|"auto_propose"|"config", ...)), exposed via REST at /api/goals*
 * (server/routes/domain.js) and consumed here through apiHelpers.goals.
 *
 * It is Concord's autonomous knowledge-work goal loop: the agent (or a user)
 * proposes a goal, an evaluation gate scores feasibility/alignment/value
 * against hard safety invariants (no negative valence, no self-preservation,
 * no harm objectives, bounded scope, knowledge-aligned), goals above the
 * evaluation threshold either auto-approve or — for high-priority/user-
 * requested goals — require explicit founder (owner/admin) consent, and a
 * heartbeat (processGoalHeartbeat, every governor tick) advances approved
 * goals to active, nudges progress, and completes/blocks them. Before this
 * panel, every one of these 12 macros was completely dark: a client wrapper
 * (apiHelpers.goals) existed with zero callers anywhere in the frontend.
 *
 * Distinct from the "Goals" tab above, which is the user's own personal/
 * team OKR tracker (a different, generic-artifact-backed data store).
 */

import { useCallback, useEffect, useState } from 'react';
import { apiHelpers } from '@/lib/api/client';
import {
  ShieldCheck, Sparkles, Loader2, ChevronDown, ChevronUp, RefreshCw,
  CheckCircle2, XCircle, PlayCircle, Gavel, Plus, AlertTriangle, Bot,
} from 'lucide-react';

// --------------- Types (mirror the server GOAL_* shapes) ---------------

interface AgentGoalSummary {
  id: string; title: string; type: string; state: string; priority: number;
  progress: number; source: string; createdAt: string;
}
interface AgentGoalDetail extends AgentGoalSummary {
  description: string;
  evaluation?: { feasibility: number; alignment: number; value: number; overall: number; evaluatedAt: string | null };
  meta?: { founderApproved?: boolean; awaitingFounderApproval?: boolean; autoGenerated?: boolean; abandonReason?: string };
  deps?: { requiredDtus: string[]; requiredGoals: string[]; blockedBy: string[] };
  progressDetail?: { current: number; target: number };
}
interface AgentStatus {
  active: AgentGoalSummary[];
  activeCount: number;
  proposalCount: number;
  stats: { proposed: number; approved: number; completed: number; abandoned: number };
  config: { maxActiveGoals: number; maxProposalsQueue: number; evaluationThreshold: number; autoProposalEnabled: boolean; founderApprovalRequired: boolean };
  invariants: Record<string, boolean>;
  readonly?: boolean;
}

const GOAL_TYPES = [
  'knowledge_synthesis', 'pattern_discovery', 'gap_filling', 'consolidation',
  'exploration', 'user_requested', 'maintenance', 'clarification',
];

const STATE_COLOR: Record<string, string> = {
  proposed: 'text-zinc-300 bg-zinc-800',
  evaluating: 'text-amber-300 bg-amber-500/10',
  approved: 'text-cyan-300 bg-cyan-500/10',
  active: 'text-emerald-300 bg-emerald-500/10',
  paused: 'text-zinc-400 bg-zinc-800',
  completed: 'text-emerald-300 bg-emerald-500/20',
  abandoned: 'text-red-300 bg-red-500/10',
  blocked: 'text-orange-300 bg-orange-500/10',
};

const STATE_FILTERS = ['all', 'proposed', 'approved', 'active', 'completed', 'abandoned', 'blocked'];

const btnCls = 'flex items-center gap-1.5 rounded border border-zinc-700 bg-zinc-900 px-2.5 py-1 text-[11px] text-zinc-200 hover:border-cyan-500/40 hover:text-cyan-300 disabled:cursor-not-allowed disabled:opacity-40';

export function AgentAutonomyPanel() {
  const [status, setStatus] = useState<AgentStatus | null>(null);
  const [goals, setGoals] = useState<AgentGoalSummary[]>([]);
  const [stateFilter, setStateFilter] = useState('all');
  const [loading, setLoading] = useState(false);
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [detail, setDetail] = useState<AgentGoalDetail | null>(null);
  const [detailLoading, setDetailLoading] = useState(false);
  const [actionError, setActionError] = useState<string | null>(null);
  const [showPropose, setShowPropose] = useState(false);
  const [proposeTitle, setProposeTitle] = useState('');
  const [proposeDesc, setProposeDesc] = useState('');
  const [proposeType, setProposeType] = useState(GOAL_TYPES[4]);
  const [proposePriority, setProposePriority] = useState(0.5);
  const [busy, setBusy] = useState(false);
  const [autoProposeResult, setAutoProposeResult] = useState<{ generated: number; proposals: { title: string }[] } | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    setActionError(null);
    try {
      const [statusRes, listRes] = await Promise.all([
        apiHelpers.goals.status(),
        apiHelpers.goals.list(stateFilter === 'all' ? { limit: 50 } : { state: stateFilter, limit: 50 }),
      ]);
      const s = statusRes.data as { ok: boolean } & AgentStatus;
      if (s?.ok !== false) setStatus(s);
      const l = listRes.data as { ok: boolean; goals: AgentGoalSummary[] };
      if (l?.ok) setGoals(l.goals || []);
    } catch (e) {
      setActionError(e instanceof Error ? e.message : 'Failed to load agent goal state.');
    } finally {
      setLoading(false);
    }
  }, [stateFilter]);

  useEffect(() => { load(); }, [load]);

  const toggleExpand = useCallback(async (id: string) => {
    if (expandedId === id) { setExpandedId(null); setDetail(null); return; }
    setExpandedId(id);
    setDetail(null);
    setDetailLoading(true);
    try {
      const r = await apiHelpers.goals.get(id);
      const d = r.data as { ok: boolean; goal: Record<string, unknown> };
      if (d?.ok && d.goal) {
        setDetail({
          id: id,
          title: String(d.goal.title || ''),
          description: String(d.goal.description || ''),
          type: String(d.goal.type || ''),
          state: String(d.goal.state || ''),
          priority: Number(d.goal.priority || 0),
          progress: Number((d.goal.progress as { current?: number; target?: number })?.current || 0) / Math.max(1, Number((d.goal.progress as { target?: number })?.target || 1)),
          source: String(d.goal.source || ''),
          createdAt: String(d.goal.createdAt || ''),
          evaluation: d.goal.evaluation as AgentGoalDetail['evaluation'],
          meta: d.goal.meta as AgentGoalDetail['meta'],
          deps: d.goal.deps as AgentGoalDetail['deps'],
          progressDetail: d.goal.progress as AgentGoalDetail['progressDetail'],
        });
      }
    } catch (e) {
      setActionError(e instanceof Error ? e.message : 'Failed to load goal detail.');
    } finally {
      setDetailLoading(false);
    }
  }, [expandedId]);

  const runAction = useCallback(async (fn: () => Promise<unknown>, refreshDetail?: string) => {
    setBusy(true);
    setActionError(null);
    try {
      const res = await fn();
      const body = (res as { data?: { ok?: boolean; error?: string } })?.data;
      if (body && body.ok === false) {
        setActionError(body.error || 'Action rejected.');
      }
      await load();
      if (refreshDetail) await toggleExpand2(refreshDetail);
    } catch (e) {
      setActionError(e instanceof Error ? e.message : 'Action failed.');
    } finally {
      setBusy(false);
    }
    // helper to re-fetch detail without collapsing
    async function toggleExpand2(id: string) {
      try {
        const r = await apiHelpers.goals.get(id);
        const d = r.data as { ok: boolean; goal: Record<string, unknown> };
        if (d?.ok && d.goal) {
          setDetail((prev) => prev ? {
            ...prev,
            state: String(d.goal.state || prev.state),
            evaluation: d.goal.evaluation as AgentGoalDetail['evaluation'],
            meta: d.goal.meta as AgentGoalDetail['meta'],
            progressDetail: d.goal.progress as AgentGoalDetail['progressDetail'],
          } : prev);
        }
      } catch { /* non-fatal */ }
    }
  }, [load]);

  const doPropose = async () => {
    if (!proposeTitle.trim()) return;
    setBusy(true);
    setActionError(null);
    try {
      const res = await apiHelpers.goals.create({
        title: proposeTitle.trim(), description: proposeDesc.trim(),
        type: proposeType, priority: proposePriority,
      });
      const body = res.data as { ok?: boolean; error?: string };
      if (body?.ok === false) setActionError(body.error || 'Proposal rejected by the invariant gate.');
      else { setProposeTitle(''); setProposeDesc(''); setShowPropose(false); await load(); }
    } catch (e) {
      setActionError(e instanceof Error ? e.message : 'Proposal failed.');
    } finally {
      setBusy(false);
    }
  };

  const doAutoPropose = async () => {
    setBusy(true);
    setActionError(null);
    try {
      const res = await apiHelpers.goals.autoPropose();
      const body = res.data as { ok?: boolean; generated?: number; proposals?: { title: string }[]; error?: string };
      if (body?.ok === false) setActionError(body.error || 'Auto-proposal is disabled.');
      else setAutoProposeResult({ generated: body?.generated || 0, proposals: body?.proposals || [] });
      await load();
    } catch (e) {
      setActionError(e instanceof Error ? e.message : 'Auto-proposal failed.');
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className="space-y-4 rounded-xl border border-zinc-800 bg-zinc-950/40 p-4">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div className="flex items-start gap-2.5">
          <div className="mt-0.5 flex h-8 w-8 flex-shrink-0 items-center justify-center rounded-lg bg-violet-500/15">
            <Bot className="h-4 w-4 text-violet-400" />
          </div>
          <div>
            <h2 className="flex items-center gap-2 text-sm font-semibold text-white">
              Agent Autonomy
              <span className="rounded bg-violet-500/15 px-1.5 py-0.5 text-[9px] uppercase tracking-wider text-violet-300">self-directed</span>
            </h2>
            <p className="max-w-2xl text-xs text-zinc-400">
              Concord&apos;s own goal loop — the agent proposes knowledge-work goals for itself, an
              evaluation gate scores them against hard safety invariants, and high-priority or
              user-requested goals wait for your (founder) approval before it acts. This is not
              your personal goal list above — it&apos;s what the system is choosing to work on.
            </p>
          </div>
        </div>
        <button onClick={() => load()} disabled={loading} className={btnCls}>
          {loading ? <Loader2 className="h-3 w-3 animate-spin" /> : <RefreshCw className="h-3 w-3" />} Refresh
        </button>
      </div>

      {actionError && (
        <div className="flex items-center gap-2 rounded border border-red-500/30 bg-red-500/10 px-3 py-2 text-xs text-red-300">
          <AlertTriangle className="h-3.5 w-3.5 flex-shrink-0" /> {actionError}
        </div>
      )}

      {status && (
        <>
          {/* Safety invariants */}
          <div className="flex flex-wrap items-center gap-1.5">
            <ShieldCheck className="h-3.5 w-3.5 text-emerald-400" />
            {Object.entries(status.invariants || {}).map(([k, v]) => (
              <span key={k} title={k} className={`rounded px-1.5 py-0.5 text-[9px] font-medium uppercase tracking-wide ${v ? 'bg-emerald-500/10 text-emerald-300' : 'bg-zinc-800 text-zinc-500'}`}>
                {k.replace(/_/g, ' ')}
              </span>
            ))}
          </div>

          {/* Stats strip */}
          <div className="grid grid-cols-2 gap-2 md:grid-cols-5">
            {[
              { label: 'Active', value: `${status.activeCount}/${status.config?.maxActiveGoals ?? '—'}` },
              { label: 'Proposed', value: status.stats?.proposed ?? 0 },
              { label: 'Approved', value: status.stats?.approved ?? 0 },
              { label: 'Completed', value: status.stats?.completed ?? 0 },
              { label: 'Abandoned', value: status.stats?.abandoned ?? 0 },
            ].map((s) => (
              <div key={s.label} className="rounded border border-zinc-800 bg-zinc-950 px-2 py-1.5 text-center">
                <div className="font-mono text-base text-violet-300">{s.value}</div>
                <div className="text-[9px] uppercase tracking-wider text-zinc-400">{s.label}</div>
              </div>
            ))}
          </div>

          {/* Config summary */}
          <div className="flex flex-wrap gap-2 text-[10px] text-zinc-400">
            <span className="rounded bg-zinc-900 px-2 py-1">Auto-proposal: <b className={status.config?.autoProposalEnabled ? 'text-emerald-300' : 'text-zinc-500'}>{status.config?.autoProposalEnabled ? 'on' : 'off'}</b></span>
            <span className="rounded bg-zinc-900 px-2 py-1">Founder consent required: <b className={status.config?.founderApprovalRequired ? 'text-amber-300' : 'text-zinc-500'}>{status.config?.founderApprovalRequired ? 'yes' : 'no'}</b></span>
            <span className="rounded bg-zinc-900 px-2 py-1">Evaluation threshold: <b className="text-cyan-300">{Math.round((status.config?.evaluationThreshold ?? 0) * 100)}%</b></span>
            {status.readonly && <span className="rounded bg-zinc-900 px-2 py-1 text-zinc-500">config is read-only for your role</span>}
          </div>
        </>
      )}

      {/* Actions row */}
      <div className="flex flex-wrap items-center gap-2">
        <button onClick={() => setShowPropose((v) => !v)} className={btnCls}>
          <Plus className="h-3 w-3" /> Propose a goal
        </button>
        <button onClick={doAutoPropose} disabled={busy} className={btnCls}>
          {busy ? <Loader2 className="h-3 w-3 animate-spin" /> : <Sparkles className="h-3 w-3" />} Run autonomous proposal pass
        </button>
        {autoProposeResult && (
          <span className="text-[11px] text-zinc-400">
            {autoProposeResult.generated === 0
              ? 'No new proposals this pass (nothing met the trigger conditions).'
              : `Generated ${autoProposeResult.generated}: ${autoProposeResult.proposals.map((p) => p.title).join('; ')}`}
          </span>
        )}
      </div>

      {showPropose && (
        <div className="grid grid-cols-1 gap-2 rounded-lg border border-zinc-800 bg-zinc-950/60 p-3 md:grid-cols-2">
          <input value={proposeTitle} onChange={(e) => setProposeTitle(e.target.value)} placeholder="Goal title" className="rounded border border-zinc-700 bg-zinc-900 px-2 py-1.5 text-xs text-white md:col-span-2" />
          <textarea value={proposeDesc} onChange={(e) => setProposeDesc(e.target.value)} placeholder="Description" className="h-16 resize-none rounded border border-zinc-700 bg-zinc-900 px-2 py-1.5 text-xs text-white md:col-span-2" />
          <select value={proposeType} onChange={(e) => setProposeType(e.target.value)} className="rounded border border-zinc-700 bg-zinc-900 px-2 py-1.5 text-xs text-white">
            {GOAL_TYPES.map((t) => <option key={t} value={t}>{t.replace(/_/g, ' ')}</option>)}
          </select>
          <label className="flex items-center gap-2 text-[10px] text-zinc-400">
            Priority
            <input type="range" min={0} max={1} step={0.05} value={proposePriority} onChange={(e) => setProposePriority(Number(e.target.value))} className="flex-1 accent-violet-500" />
            <span className="font-mono text-violet-300">{Math.round(proposePriority * 100)}%</span>
          </label>
          <button onClick={doPropose} disabled={busy || !proposeTitle.trim()} className={`${btnCls} justify-center md:col-span-2`}>
            {busy ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Plus className="h-3.5 w-3.5" />} Submit proposal
          </button>
          {proposePriority > 0.8 && (
            <p className="text-[10px] text-amber-400 md:col-span-2">High-priority proposals require founder approval before they can activate.</p>
          )}
        </div>
      )}

      {/* State filter */}
      <div className="flex flex-wrap gap-1">
        {STATE_FILTERS.map((f) => (
          <button
            key={f}
            onClick={() => setStateFilter(f)}
            className={`rounded-full px-2.5 py-1 text-[10px] font-medium capitalize transition-colors ${stateFilter === f ? 'bg-violet-500/20 text-violet-300' : 'bg-zinc-900 text-zinc-500 hover:bg-zinc-800'}`}
          >
            {f}
          </button>
        ))}
      </div>

      {/* Goal list */}
      <div className="space-y-1.5">
        {goals.map((g) => {
          const isExpanded = expandedId === g.id;
          return (
            <div key={g.id} className="rounded border border-zinc-800 bg-zinc-950">
              <button onClick={() => toggleExpand(g.id)} className="flex w-full items-center gap-2 px-2.5 py-1.5 text-left">
                <span className={`rounded px-1.5 py-0.5 text-[9px] font-medium uppercase ${STATE_COLOR[g.state] || 'bg-zinc-800 text-zinc-400'}`}>{g.state}</span>
                <span className="min-w-0 flex-1 truncate text-[12px] text-zinc-200">{g.title}</span>
                <span className="text-[9px] text-zinc-500">{g.type.replace(/_/g, ' ')}</span>
                <span className="text-[9px] text-zinc-500">{Math.round((g.progress || 0) * 100)}%</span>
                {isExpanded ? <ChevronUp className="h-3.5 w-3.5 text-zinc-500" /> : <ChevronDown className="h-3.5 w-3.5 text-zinc-500" />}
              </button>
              {isExpanded && (
                <div className="space-y-2 border-t border-zinc-800 px-2.5 py-2">
                  {detailLoading && <div className="flex items-center gap-2 text-[11px] text-zinc-500"><Loader2 className="h-3 w-3 animate-spin" /> Loading…</div>}
                  {detail && detail.id === g.id && (
                    <>
                      {detail.description && <p className="text-[11px] text-zinc-400">{detail.description}</p>}
                      {detail.evaluation?.evaluatedAt && (
                        <div className="grid grid-cols-4 gap-1.5">
                          {[
                            ['Feasibility', detail.evaluation.feasibility],
                            ['Alignment', detail.evaluation.alignment],
                            ['Value', detail.evaluation.value],
                            ['Overall', detail.evaluation.overall],
                          ].map(([label, v]) => (
                            <div key={label as string} className="rounded bg-zinc-900 px-1.5 py-1 text-center">
                              <div className="font-mono text-[11px] text-cyan-300">{Math.round((v as number) * 100)}%</div>
                              <div className="text-[8px] uppercase text-zinc-500">{label}</div>
                            </div>
                          ))}
                        </div>
                      )}
                      {detail.meta?.awaitingFounderApproval && !detail.meta?.founderApproved && (
                        <div className="flex items-center gap-1.5 rounded border border-amber-500/30 bg-amber-500/10 px-2 py-1 text-[10px] text-amber-300">
                          <Gavel className="h-3 w-3" /> Awaiting founder approval
                        </div>
                      )}
                      {detail.meta?.abandonReason && (
                        <p className="text-[10px] text-zinc-500">Abandoned: {detail.meta.abandonReason}</p>
                      )}
                      <div className="flex flex-wrap gap-1.5">
                        {g.state === 'proposed' && !detail.meta?.awaitingFounderApproval && (
                          <button disabled={busy} onClick={() => runAction(() => apiHelpers.goals.evaluate(g.id), g.id)} className={btnCls}><PlayCircle className="h-3 w-3" /> Evaluate</button>
                        )}
                        {g.state === 'proposed' && detail.meta?.awaitingFounderApproval && !detail.meta?.founderApproved && (
                          <button disabled={busy} onClick={() => runAction(() => apiHelpers.goals.approve(g.id), g.id)} className={btnCls}><Gavel className="h-3 w-3" /> Approve (founder)</button>
                        )}
                        {g.state === 'approved' && (
                          <button disabled={busy} onClick={() => runAction(() => apiHelpers.goals.activate(g.id), g.id)} className={btnCls}><PlayCircle className="h-3 w-3" /> Activate</button>
                        )}
                        {g.state === 'active' && (
                          <>
                            <button disabled={busy} onClick={() => runAction(() => apiHelpers.goals.progress(g.id, { progress: 1, note: 'manual bump' }), g.id)} className={btnCls}><Sparkles className="h-3 w-3" /> +1 progress</button>
                            <button disabled={busy} onClick={() => runAction(() => apiHelpers.goals.complete(g.id), g.id)} className={btnCls}><CheckCircle2 className="h-3 w-3" /> Complete</button>
                          </>
                        )}
                        {!['completed', 'abandoned'].includes(g.state) && (
                          <button disabled={busy} onClick={() => runAction(() => apiHelpers.goals.abandon(g.id, 'user_requested'), g.id)} className={btnCls}><XCircle className="h-3 w-3" /> Abandon</button>
                        )}
                      </div>
                    </>
                  )}
                </div>
              )}
            </div>
          );
        })}
        {goals.length === 0 && !loading && (
          <p className="rounded border border-dashed border-zinc-800 p-4 text-center text-[11px] text-zinc-500">
            No {stateFilter === 'all' ? '' : `${stateFilter} `}agent goals yet. Propose one, or run an
            autonomous proposal pass above.
          </p>
        )}
      </div>
    </div>
  );
}
