// tests/depth/engineering-connection-transformer-behavior.test.js
//
// REAL behavioral tests for the two new engineering macros that close the
// docs/WAVE4_INVENTORY.md row: `boltedConnection`/`transformerSizing` real
// AISC/ANSI math (server/lib/compute/engineering-compute.js) were previously
// unreachable at the macro layer — no registered macro called either
// function. `engineering.connectionCheck` and `engineering.transformerSizing`
// (server/domains/engineering.js) are thin passthroughs to those real
// functions; no math is re-derived here or in the macro layer.
//
// Expected numeric values below were generated by calling the real compute
// functions directly (CLAUDE.md "compute-don't-guess"), not hand-arithmetic:
//   node -e "import('./lib/compute/engineering-compute.js').then(m => {
//     console.log(m.boltedConnection({ boltDiameter: 0.75, boltGrade: 'a325', numBolts: 4, loadType: 'single' }));
//     console.log(m.transformerSizing({ loadKva: 100, voltage: 480, phase: 3, powerFactor: 0.9, growthFactor: 1.25 }));
//   });"
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { lensRun } from "./_harness.js";

describe("engineering — connectionCheck (real AISC bolted-connection shear)", () => {
  it("4× 3/4in A325 bolts, single shear: matches the real compute function's output exactly", async () => {
    const r = await lensRun("engineering", "connectionCheck", {
      data: { boltDiameter: 0.75, boltGrade: "a325", numBolts: 4, loadType: "single" },
    });
    assert.equal(r.ok, true);
    // Hand-verified via direct node invocation of boltedConnection() — see file header.
    assert.ok(Math.abs(r.result.value - 84.82300164692441) < 1e-9);
    assert.equal(r.result.unit, "kips");
    assert.equal(r.result.formula, "R = Fv·Ab·n·planes");
    assert.equal(r.result.shearPlanes, 1);
    assert.ok(Math.abs(r.result.perBoltKips - 21.205750411731103) < 1e-9);
    assert.ok(Math.abs(r.result.boltAreaSqIn - 0.44178646691106466) < 1e-9);
  });

  it("double shear doubles the per-bolt capacity (loadType: 'double')", async () => {
    const single = await lensRun("engineering", "connectionCheck", {
      data: { boltDiameter: 0.75, boltGrade: "a325", numBolts: 1, loadType: "single" },
    });
    const double = await lensRun("engineering", "connectionCheck", {
      data: { boltDiameter: 0.75, boltGrade: "a325", numBolts: 1, loadType: "double" },
    });
    assert.equal(single.ok, true);
    assert.equal(double.ok, true);
    assert.equal(double.result.shearPlanes, 2);
    assert.ok(Math.abs(double.result.value - single.result.value * 2) < 1e-9);
  });

  it("A490 bolts carry more shear than A307 bolts for the same geometry (fv 60 vs 24 ksi)", async () => {
    const a307 = await lensRun("engineering", "connectionCheck", {
      data: { boltDiameter: 0.5, boltGrade: "a307", numBolts: 2 },
    });
    const a490 = await lensRun("engineering", "connectionCheck", {
      data: { boltDiameter: 0.5, boltGrade: "a490", numBolts: 2 },
    });
    assert.equal(a307.ok, true);
    assert.equal(a490.ok, true);
    assert.ok(a490.result.value > a307.result.value);
    // 60/24 = 2.5x ratio, exact since both share the same area/planes/numBolts.
    assert.ok(Math.abs(a490.result.value / a307.result.value - 2.5) < 1e-9);
  });

  it("rejects a non-positive bolt diameter as an honest failure, never a fabricated success", async () => {
    const r = await lensRun("engineering", "connectionCheck", {
      data: { boltDiameter: 0, numBolts: 4 },
    });
    assert.equal(r.result.ok, false);
    assert.match(String(r.result.error), /positive values required/i);
  });

  it("rejects a non-numeric numBolts as an honest failure", async () => {
    const r = await lensRun("engineering", "connectionCheck", {
      data: { boltDiameter: 0.5, numBolts: "x" },
    });
    assert.equal(r.result.ok, false);
    assert.match(String(r.result.error), /numeric required/i);
  });

  it("rejects a missing boltDiameter entirely (undefined input)", async () => {
    const r = await lensRun("engineering", "connectionCheck", { data: { numBolts: 4 } });
    assert.equal(r.result.ok, false);
    assert.match(String(r.result.error), /numeric required/i);
  });
});

describe("engineering — transformerSizing (real ANSI kVA-ladder sizing)", () => {
  it("100kVA load at 480V 3-phase with default 1.25 growth: matches the real compute function's output exactly", async () => {
    const r = await lensRun("engineering", "transformerSizing", {
      data: { loadKva: 100, voltage: 480, phase: 3, powerFactor: 0.9, growthFactor: 1.25 },
    });
    assert.equal(r.ok, true);
    // Hand-verified via direct node invocation of transformerSizing() — see file header.
    // required = 100*1.25 = 125 -> next ANSI standard size is 150 (not 112.5).
    assert.equal(r.result.value, 150);
    assert.equal(r.result.unit, "kVA");
    assert.equal(r.result.requiredKva, 125);
    assert.equal(r.result.selectedKva, 150);
    assert.ok(Math.abs(r.result.primaryAmps - 180.42195912175808) < 1e-9);
    assert.equal(r.result.powerFactor, 0.9);
  });

  it("single-phase primaryAmps formula differs from 3-phase (no sqrt(3) factor)", async () => {
    const r = await lensRun("engineering", "transformerSizing", {
      data: { loadKva: 20, voltage: 240, phase: 1, growthFactor: 1 },
    });
    assert.equal(r.ok, true);
    // required=20 -> next standard is 30kVA. primaryAmps = 30000/240 = 125 exact.
    assert.equal(r.result.selectedKva, 30);
    assert.equal(r.result.primaryAmps, 125);
  });

  it("an exact ladder boundary selects that same size, not the next one up", async () => {
    const r = await lensRun("engineering", "transformerSizing", {
      data: { loadKva: 75, voltage: 480, phase: 3, growthFactor: 1 },
    });
    assert.equal(r.ok, true);
    assert.equal(r.result.requiredKva, 75);
    assert.equal(r.result.selectedKva, 75); // ladder includes 75 exactly
  });

  it("rejects a non-positive loadKva as an honest failure, never a fabricated success", async () => {
    const r = await lensRun("engineering", "transformerSizing", {
      data: { loadKva: -5, voltage: 480 },
    });
    assert.equal(r.result.ok, false);
    assert.match(String(r.result.error), /loadKva must be > 0/i);
  });

  it("rejects a missing voltage as an honest failure", async () => {
    const r = await lensRun("engineering", "transformerSizing", { data: { loadKva: 50 } });
    assert.equal(r.result.ok, false);
    assert.match(String(r.result.error), /voltage must be > 0/i);
  });
});
