// server/migrations/452_evo_assets_trellis_source.js
//
// Admit 'trellis' as an evo_assets source: organic assets generated by
// Concord's own pipeline (lib/asset-gen/organic/) — FLUX.1-schnell concept →
// TRELLIS.2 / TRELLIS image-to-3D (Microsoft, MIT) on Hugging Face ZeroGPU →
// Concord normalize + budget LODs. Provenance must not be stamped as
// 'authored' or 'evolved' (see 448/451 for why that workaround was retired).
// The rebuild itself lives in ./_evo-assets-source-rebuild.js.

import { ensureEvoAssetSources } from "./_evo-assets-source-rebuild.js";

export const SOURCES_452 = Object.freeze([
  "kenney", "polyhaven", "ambientcg", "os3a", "sketchfab",
  "authored", "evolved", "concordia", "github", "hubkit",
  "meshy", "tripo", "trellis",
]);

export function up(db) {
  ensureEvoAssetSources(db, SOURCES_452, "evo_assets_v6");
}

export function down() {
  // Forward-only: narrowing the CHECK back would reject existing trellis rows.
}

export const description = "Admit 'trellis' as an evo_assets source for Concord-generated organic assets";
