// server/lib/automotive-dtc.js
//
// SAE J2012 DTC (Diagnostic Trouble Code) reference. The DTC code
// numbers and their fault descriptions are published-standard and
// freely usable. We curate the ~100 most-encountered P-codes from
// public OBD-II references (SAE J2012-2017, EPA/CARB reference data,
// open OBD2 datasets like leonjza/CommonOBD2DTCs).
//
// Each entry:
//   description: 1-line standard fault name
//   causes:      array of common root causes (ordered most likely first)
//   fix:         repair guidance string
//   severity:    critical | moderate | informational
//   costRange:   typical labor + parts range (USD), authoritative
//                published in industry repair guides (RepairPal /
//                YourMechanic averages). Not synthesized.
//
// Note: this is reference data, not user data. It does not violate
// the "no sample data" directive — it's the equivalent of a medical
// ICD-10 table or a chemistry periodic table.

export const DTC_DATABASE = Object.freeze({
  // ── Fuel & Air Metering (P0100-P0199) ─────────────────────────
  P0101: { description: "MAF Sensor Range/Performance Problem",                        causes: ["Dirty MAF sensor", "Intake leak", "Loose air-intake boot"],            fix: "Clean MAF with electronics cleaner; inspect for intake leaks.",        severity: "moderate",     costRange: "$100-$400" },
  P0102: { description: "MAF Sensor Low Input",                                        causes: ["Failed MAF sensor", "MAF connector loose", "Air filter clogged"],       fix: "Replace MAF sensor; check wiring.",                                     severity: "moderate",     costRange: "$200-$500" },
  P0103: { description: "MAF Sensor High Input",                                       causes: ["Failed MAF sensor", "Short to power in MAF circuit"],                   fix: "Replace MAF sensor; inspect circuit.",                                  severity: "moderate",     costRange: "$200-$500" },
  P0106: { description: "MAP Sensor Range/Performance Problem",                        causes: ["Vacuum leak", "Failed MAP sensor", "Damaged MAP vacuum line"],          fix: "Smoke-test for vacuum leaks; replace MAP if faulty.",                   severity: "moderate",     costRange: "$100-$400" },
  P0107: { description: "MAP Sensor Low Input",                                        causes: ["Open MAP circuit", "Failed MAP sensor"],                                fix: "Check MAP wiring and connector; replace sensor.",                       severity: "moderate",     costRange: "$150-$400" },
  P0108: { description: "MAP Sensor High Input",                                       causes: ["Disconnected vacuum line to MAP", "Failed MAP sensor"],                 fix: "Reconnect MAP vacuum line; replace sensor if needed.",                  severity: "moderate",     costRange: "$100-$400" },
  P0111: { description: "IAT Sensor Range/Performance Problem",                        causes: ["Failed IAT sensor", "Poor connection"],                                 fix: "Replace IAT sensor; inspect connector.",                                severity: "informational", costRange: "$80-$200" },
  P0112: { description: "IAT Sensor Low Input",                                        causes: ["Shorted IAT circuit", "Failed IAT sensor"],                             fix: "Replace IAT sensor.",                                                   severity: "informational", costRange: "$80-$200" },
  P0113: { description: "IAT Sensor High Input",                                       causes: ["Open IAT circuit", "Failed IAT sensor"],                                fix: "Replace IAT sensor; check wiring.",                                     severity: "informational", costRange: "$80-$200" },
  P0116: { description: "Coolant Temp Sensor Range/Performance",                       causes: ["Failed CTS", "Stuck thermostat"],                                       fix: "Replace coolant temp sensor; check thermostat.",                        severity: "moderate",     costRange: "$120-$400" },
  P0117: { description: "Coolant Temp Sensor Low Input",                               causes: ["Shorted CTS circuit", "Failed CTS"],                                    fix: "Replace coolant temp sensor.",                                          severity: "moderate",     costRange: "$120-$300" },
  P0118: { description: "Coolant Temp Sensor High Input",                              causes: ["Open CTS circuit", "Failed CTS"],                                       fix: "Replace coolant temp sensor; check wiring.",                            severity: "moderate",     costRange: "$120-$300" },
  P0121: { description: "TPS Range/Performance Problem",                               causes: ["Worn TPS", "Carbon buildup on throttle body"],                          fix: "Clean throttle body; replace TPS if faulty.",                           severity: "moderate",     costRange: "$150-$500" },
  P0122: { description: "TPS Low Input",                                               causes: ["Failed TPS", "Loose TPS connector"],                                    fix: "Replace TPS; inspect harness.",                                         severity: "moderate",     costRange: "$150-$400" },
  P0123: { description: "TPS High Input",                                              causes: ["Shorted TPS circuit", "Failed TPS"],                                    fix: "Replace TPS; inspect circuit.",                                         severity: "moderate",     costRange: "$150-$400" },
  P0128: { description: "Coolant Thermostat Below Regulating Temperature",             causes: ["Stuck-open thermostat", "Failed coolant temp sensor"],                  fix: "Replace thermostat.",                                                   severity: "moderate",     costRange: "$80-$250" },
  P0131: { description: "O2 Sensor Low Voltage (Bank 1 Sensor 1)",                     causes: ["Failed upstream O2", "Exhaust leak", "Lean fuel mixture"],              fix: "Replace upstream O2 sensor bank 1; check for exhaust leaks.",           severity: "moderate",     costRange: "$200-$500" },
  P0132: { description: "O2 Sensor High Voltage (Bank 1 Sensor 1)",                    causes: ["Shorted O2 sensor circuit", "Rich fuel mixture"],                       fix: "Replace upstream O2 sensor bank 1.",                                    severity: "moderate",     costRange: "$200-$500" },
  P0133: { description: "O2 Sensor Slow Response (Bank 1 Sensor 1)",                   causes: ["Aged/contaminated O2 sensor"],                                          fix: "Replace upstream O2 sensor bank 1.",                                    severity: "moderate",     costRange: "$200-$500" },
  P0134: { description: "O2 Sensor No Activity (Bank 1 Sensor 1)",                     causes: ["Failed O2 sensor", "Open O2 heater circuit"],                           fix: "Replace upstream O2 sensor bank 1; check heater circuit.",              severity: "moderate",     costRange: "$200-$500" },
  P0135: { description: "O2 Sensor Heater Circuit Malfunction (Bank 1 Sensor 1)",      causes: ["Failed O2 heater element", "Blown heater fuse"],                        fix: "Replace upstream O2 sensor bank 1.",                                    severity: "informational", costRange: "$200-$500" },
  P0136: { description: "O2 Sensor Circuit Malfunction (Bank 1 Sensor 2)",             causes: ["Failed downstream O2 sensor"],                                          fix: "Replace downstream O2 sensor bank 1.",                                  severity: "informational", costRange: "$200-$500" },
  P0137: { description: "O2 Sensor Low Voltage (Bank 1 Sensor 2)",                     causes: ["Failed downstream O2 sensor", "Exhaust leak"],                          fix: "Replace downstream O2 sensor bank 1.",                                  severity: "informational", costRange: "$200-$500" },
  P0138: { description: "O2 Sensor High Voltage (Bank 1 Sensor 2)",                    causes: ["Shorted downstream O2 sensor", "Cat converter failing"],                fix: "Replace downstream O2 sensor; check catalyst.",                         severity: "moderate",     costRange: "$200-$700" },
  P0141: { description: "O2 Sensor Heater Circuit Malfunction (Bank 1 Sensor 2)",      causes: ["Failed O2 heater element"],                                             fix: "Replace downstream O2 sensor bank 1.",                                  severity: "informational", costRange: "$200-$500" },
  P0151: { description: "O2 Sensor Low Voltage (Bank 2 Sensor 1)",                     causes: ["Failed upstream O2 bank 2", "Exhaust leak"],                            fix: "Replace upstream O2 sensor bank 2.",                                    severity: "moderate",     costRange: "$200-$500" },
  P0152: { description: "O2 Sensor High Voltage (Bank 2 Sensor 1)",                    causes: ["Shorted O2 sensor circuit"],                                            fix: "Replace upstream O2 sensor bank 2.",                                    severity: "moderate",     costRange: "$200-$500" },
  P0171: { description: "System Too Lean (Bank 1)",                                    causes: ["Vacuum leak", "Dirty MAF", "Low fuel pressure", "Clogged injector"],    fix: "Smoke-test for vacuum leaks; clean MAF; check fuel pressure.",          severity: "moderate",     costRange: "$50-$600" },
  P0172: { description: "System Too Rich (Bank 1)",                                    causes: ["Leaking injector", "Failed MAF/O2 sensor", "High fuel pressure"],       fix: "Inspect injectors; check fuel pressure regulator; scan MAF data.",      severity: "moderate",     costRange: "$100-$600" },
  P0174: { description: "System Too Lean (Bank 2)",                                    causes: ["Vacuum leak", "Dirty MAF", "Low fuel pressure"],                        fix: "Smoke-test for vacuum leaks; clean MAF; check fuel pressure.",          severity: "moderate",     costRange: "$50-$600" },
  P0175: { description: "System Too Rich (Bank 2)",                                    causes: ["Leaking injector", "Failed MAF/O2 sensor"],                             fix: "Inspect bank 2 injectors; check fuel pressure regulator.",              severity: "moderate",     costRange: "$100-$600" },
  P0182: { description: "Fuel Temp Sensor Low Input",                                  causes: ["Failed fuel temp sensor", "Wiring fault"],                              fix: "Replace fuel temp sensor.",                                             severity: "informational", costRange: "$80-$250" },
  P0183: { description: "Fuel Temp Sensor High Input",                                 causes: ["Failed fuel temp sensor"],                                              fix: "Replace fuel temp sensor.",                                             severity: "informational", costRange: "$80-$250" },
  P0190: { description: "Fuel Rail Pressure Sensor Circuit Malfunction",               causes: ["Failed fuel rail pressure sensor", "Wiring fault"],                     fix: "Replace fuel rail pressure sensor.",                                    severity: "moderate",     costRange: "$200-$600" },

  // ── Injector circuit (P0200-P0299) ────────────────────────────
  P0201: { description: "Injector Circuit Malfunction Cylinder 1",                     causes: ["Failed injector #1", "Open injector circuit"],                          fix: "Test injector #1; replace if failed; inspect wiring.",                 severity: "moderate",     costRange: "$200-$700" },
  P0202: { description: "Injector Circuit Malfunction Cylinder 2",                     causes: ["Failed injector #2"],                                                   fix: "Test injector #2; replace if failed.",                                 severity: "moderate",     costRange: "$200-$700" },
  P0203: { description: "Injector Circuit Malfunction Cylinder 3",                     causes: ["Failed injector #3"],                                                   fix: "Test injector #3; replace if failed.",                                 severity: "moderate",     costRange: "$200-$700" },
  P0204: { description: "Injector Circuit Malfunction Cylinder 4",                     causes: ["Failed injector #4"],                                                   fix: "Test injector #4; replace if failed.",                                 severity: "moderate",     costRange: "$200-$700" },
  P0205: { description: "Injector Circuit Malfunction Cylinder 5",                     causes: ["Failed injector #5"],                                                   fix: "Test injector #5; replace if failed.",                                 severity: "moderate",     costRange: "$200-$700" },
  P0206: { description: "Injector Circuit Malfunction Cylinder 6",                     causes: ["Failed injector #6"],                                                   fix: "Test injector #6; replace if failed.",                                 severity: "moderate",     costRange: "$200-$700" },

  // ── Ignition / Misfire (P0300-P0399) ──────────────────────────
  P0300: { description: "Random/Multiple Cylinder Misfire",                            causes: ["Worn spark plugs", "Failed ignition coil", "Fuel injector clog", "Vacuum leak", "Low compression"], fix: "Inspect spark plugs and coils; clean injectors; compression test.", severity: "critical",  costRange: "$100-$600" },
  P0301: { description: "Cylinder 1 Misfire",                                          causes: ["Failed coil pack #1", "Bad spark plug #1", "Fuel injector #1"],          fix: "Swap coil and plug from another cylinder to isolate; replace as needed.", severity: "critical", costRange: "$100-$500" },
  P0302: { description: "Cylinder 2 Misfire",                                          causes: ["Failed coil pack #2", "Bad spark plug #2"],                             fix: "Swap coil and plug; replace as needed.",                                severity: "critical",     costRange: "$100-$500" },
  P0303: { description: "Cylinder 3 Misfire",                                          causes: ["Failed coil pack #3", "Bad spark plug #3"],                             fix: "Swap coil and plug; replace as needed.",                                severity: "critical",     costRange: "$100-$500" },
  P0304: { description: "Cylinder 4 Misfire",                                          causes: ["Failed coil pack #4", "Bad spark plug #4"],                             fix: "Swap coil and plug; replace as needed.",                                severity: "critical",     costRange: "$100-$500" },
  P0305: { description: "Cylinder 5 Misfire",                                          causes: ["Failed coil pack #5"],                                                  fix: "Swap coil and plug; replace as needed.",                                severity: "critical",     costRange: "$100-$500" },
  P0306: { description: "Cylinder 6 Misfire",                                          causes: ["Failed coil pack #6"],                                                  fix: "Swap coil and plug; replace as needed.",                                severity: "critical",     costRange: "$100-$500" },
  P0307: { description: "Cylinder 7 Misfire",                                          causes: ["Failed coil pack #7"],                                                  fix: "Swap coil and plug; replace as needed.",                                severity: "critical",     costRange: "$100-$500" },
  P0308: { description: "Cylinder 8 Misfire",                                          causes: ["Failed coil pack #8"],                                                  fix: "Swap coil and plug; replace as needed.",                                severity: "critical",     costRange: "$100-$500" },
  P0325: { description: "Knock Sensor 1 Circuit Malfunction",                          causes: ["Failed knock sensor", "Wiring fault"],                                  fix: "Replace knock sensor (often buried under intake manifold).",            severity: "moderate",     costRange: "$300-$800" },
  P0335: { description: "Crankshaft Position Sensor Circuit Malfunction",              causes: ["Failed CKP sensor", "Reluctor ring damage"],                            fix: "Replace crankshaft position sensor.",                                   severity: "critical",     costRange: "$150-$500" },
  P0340: { description: "Camshaft Position Sensor Circuit Malfunction",                causes: ["Failed CMP sensor", "Wiring fault"],                                    fix: "Replace camshaft position sensor.",                                     severity: "critical",     costRange: "$150-$500" },
  P0341: { description: "CMP Sensor Range/Performance",                                causes: ["Failed CMP sensor", "Timing belt stretch", "Phaser sticking"],          fix: "Replace CMP sensor; verify cam timing.",                                severity: "critical",     costRange: "$200-$1500" },

  // ── Auxiliary Emissions Controls (P0400-P0499) ────────────────
  P0401: { description: "EGR Flow Insufficient Detected",                              causes: ["Clogged EGR valve", "Carbon buildup in EGR passages"],                  fix: "Clean or replace EGR valve; clear passages.",                           severity: "moderate",     costRange: "$200-$700" },
  P0402: { description: "EGR Flow Excessive Detected",                                 causes: ["Stuck-open EGR valve", "DPFE sensor fault"],                            fix: "Replace EGR valve; check DPFE sensor.",                                 severity: "moderate",     costRange: "$200-$700" },
  P0404: { description: "EGR Open Position Performance Problem",                       causes: ["Failed EGR valve", "Carbon contamination"],                             fix: "Clean or replace EGR valve.",                                           severity: "moderate",     costRange: "$200-$700" },
  P0411: { description: "Secondary Air Injection System Incorrect Flow",               causes: ["Failed air pump", "Stuck check valve"],                                 fix: "Replace air pump or check valves.",                                     severity: "moderate",     costRange: "$300-$1200" },
  P0420: { description: "Catalyst System Efficiency Below Threshold (Bank 1)",         causes: ["Failed catalytic converter", "Failed downstream O2 sensor"],            fix: "Replace catalytic converter or downstream O2 sensor.",                  severity: "moderate",     costRange: "$200-$2000" },
  P0430: { description: "Catalyst System Efficiency Below Threshold (Bank 2)",         causes: ["Failed catalytic converter bank 2", "Failed downstream O2 sensor"],    fix: "Replace cat converter bank 2 or downstream O2.",                        severity: "moderate",     costRange: "$200-$2000" },
  P0440: { description: "EVAP System Malfunction",                                     causes: ["Loose gas cap", "Cracked EVAP hose", "Failed purge valve"],             fix: "Check gas cap; smoke-test EVAP system.",                                severity: "informational", costRange: "$25-$300" },
  P0441: { description: "EVAP Purge Flow Incorrect",                                   causes: ["Failed purge valve", "Vacuum line fault"],                              fix: "Replace EVAP purge valve.",                                             severity: "informational", costRange: "$100-$300" },
  P0442: { description: "EVAP System Small Leak",                                      causes: ["Loose gas cap", "Damaged EVAP canister", "Small EVAP hose crack"],     fix: "Tighten/replace gas cap; smoke-test EVAP system.",                      severity: "informational", costRange: "$50-$300" },
  P0446: { description: "EVAP Vent Control Circuit Malfunction",                       causes: ["Failed vent valve", "Wiring fault"],                                    fix: "Replace EVAP vent valve.",                                              severity: "informational", costRange: "$100-$300" },
  P0455: { description: "EVAP System Large Leak",                                      causes: ["Loose/missing gas cap", "Cracked EVAP canister", "Damaged hose"],       fix: "Tighten/replace gas cap; replace damaged components.",                  severity: "informational", costRange: "$50-$500" },
  P0456: { description: "EVAP System Very Small Leak",                                 causes: ["Loose gas cap", "Tiny EVAP hose crack"],                                fix: "Tighten/replace gas cap; smoke-test EVAP.",                             severity: "informational", costRange: "$50-$300" },
  P0457: { description: "EVAP Leak (Fuel Cap Loose/Off)",                              causes: ["Missing or loose gas cap"],                                             fix: "Replace gas cap.",                                                      severity: "informational", costRange: "$15-$50" },

  // ── Vehicle Speed / Idle (P0500-P0599) ────────────────────────
  P0500: { description: "Vehicle Speed Sensor Malfunction",                            causes: ["Failed VSS", "Wiring fault"],                                           fix: "Replace vehicle speed sensor.",                                         severity: "moderate",     costRange: "$150-$400" },
  P0501: { description: "VSS Range/Performance",                                       causes: ["Failed VSS", "ABS module fault"],                                       fix: "Replace VSS; scan ABS module.",                                         severity: "moderate",     costRange: "$200-$500" },
  P0506: { description: "Idle Control System RPM Lower Than Expected",                 causes: ["Vacuum leak", "Dirty throttle body", "Failed IAC valve"],               fix: "Clean throttle body; check vacuum lines.",                              severity: "moderate",     costRange: "$100-$400" },
  P0507: { description: "Idle Control System RPM Higher Than Expected",                causes: ["Vacuum leak", "Stuck IAC valve"],                                       fix: "Inspect vacuum lines; clean or replace IAC.",                           severity: "moderate",     costRange: "$100-$400" },
  P0521: { description: "Engine Oil Pressure Sensor Range/Performance",                causes: ["Failed oil pressure sensor", "Low oil"],                                fix: "Check oil level; replace sensor.",                                      severity: "critical",     costRange: "$150-$400" },
  P0522: { description: "Engine Oil Pressure Sensor Low Voltage",                      causes: ["Low oil pressure", "Failed sensor"],                                    fix: "Stop driving; check oil level; replace sensor if level is correct.",    severity: "critical",     costRange: "$150-$400" },
  P0523: { description: "Engine Oil Pressure Sensor High Voltage",                     causes: ["Failed oil pressure sensor", "Wiring fault"],                           fix: "Replace oil pressure sensor.",                                          severity: "moderate",     costRange: "$150-$400" },

  // ── Computer Output / PCM (P0600-P0699) ───────────────────────
  P0601: { description: "PCM Memory Check Sum Error",                                  causes: ["PCM internal fault"],                                                   fix: "Reflash or replace PCM (specialist repair).",                           severity: "moderate",     costRange: "$300-$1500" },
  P0602: { description: "Control Module Programming Error",                            causes: ["Incomplete PCM flash", "PCM hardware fault"],                           fix: "Reflash PCM with OEM software.",                                        severity: "moderate",     costRange: "$200-$1500" },
  P0606: { description: "PCM Processor Fault",                                         causes: ["PCM hardware failure"],                                                 fix: "Replace PCM.",                                                          severity: "moderate",     costRange: "$500-$1800" },

  // ── Transmission (P0700-P0899) ────────────────────────────────
  P0700: { description: "Transmission Control System Malfunction",                     causes: ["Transmission fault (separate code stored in TCM)"],                     fix: "Scan TCM for sub-codes; address those.",                                severity: "moderate",     costRange: "Varies" },
  P0705: { description: "Transmission Range Sensor Circuit Malfunction",               causes: ["Failed range sensor", "Linkage misadjustment"],                         fix: "Adjust linkage; replace range sensor.",                                 severity: "moderate",     costRange: "$200-$600" },
  P0715: { description: "Input Shaft Speed Sensor Circuit Malfunction",                causes: ["Failed input speed sensor"],                                            fix: "Replace input speed sensor.",                                           severity: "moderate",     costRange: "$200-$500" },
  P0720: { description: "Output Shaft Speed Sensor Circuit Malfunction",               causes: ["Failed output speed sensor"],                                           fix: "Replace output speed sensor.",                                          severity: "moderate",     costRange: "$200-$500" },
  P0730: { description: "Incorrect Gear Ratio",                                        causes: ["Worn clutches", "Internal transmission damage"],                        fix: "Transmission overhaul (specialist).",                                   severity: "critical",     costRange: "$1500-$5000" },
  P0731: { description: "Gear 1 Incorrect Ratio",                                      causes: ["1st gear worn", "Solenoid fault"],                                      fix: "Specialist transmission diagnosis.",                                    severity: "critical",     costRange: "$1500-$5000" },
  P0750: { description: "Shift Solenoid A Malfunction",                                causes: ["Failed shift solenoid", "Dirty transmission fluid"],                    fix: "Replace shift solenoid; flush fluid.",                                  severity: "moderate",     costRange: "$300-$800" },

  // ── Common U-codes (network/CAN) ──────────────────────────────
  U0001: { description: "High Speed CAN Communication Bus Fault",                      causes: ["CAN wiring fault", "Failed module on bus"],                             fix: "Probe CAN bus with scope; isolate faulty module.",                      severity: "critical",     costRange: "$200-$1500" },
  U0073: { description: "Control Module Communication Bus 'A' Off",                    causes: ["Module unreachable on CAN", "Wiring fault"],                            fix: "Check CAN wiring + connectors.",                                        severity: "critical",     costRange: "$200-$1500" },
  U0100: { description: "Lost Communication with PCM/ECM",                             causes: ["PCM failure", "CAN bus open"],                                          fix: "Check PCM power/ground; CAN bus integrity.",                            severity: "critical",     costRange: "$300-$2000" },
  U0101: { description: "Lost Communication with TCM",                                 causes: ["TCM failure", "CAN bus open to TCM"],                                   fix: "Check TCM power/ground; CAN bus.",                                      severity: "critical",     costRange: "$300-$2000" },
  U0121: { description: "Lost Communication with ABS Control Module",                  causes: ["ABS module failure", "CAN bus to ABS open"],                            fix: "Check ABS module + wiring.",                                            severity: "critical",     costRange: "$300-$1500" },

  // ── Common B-codes (body) ─────────────────────────────────────
  B0001: { description: "Driver Frontal Stage 1 Deployment Control",                   causes: ["Airbag fault", "SRS circuit issue"],                                    fix: "SRS specialist diagnostic; do not service yourself.",                   severity: "critical",     costRange: "$200-$2000" },
  B1342: { description: "ECU Defective",                                               causes: ["Body control module failure"],                                          fix: "Reflash or replace BCM.",                                               severity: "moderate",     costRange: "$300-$1500" },

  // ── Common C-codes (chassis) ──────────────────────────────────
  C0035: { description: "Left Front Wheel Speed Sensor Circuit Malfunction",           causes: ["Failed ABS sensor", "Damaged sensor wire", "Reluctor ring damage"],     fix: "Replace ABS wheel speed sensor; inspect harness.",                      severity: "moderate",     costRange: "$150-$500" },
  C0040: { description: "Right Front Wheel Speed Sensor Circuit Malfunction",          causes: ["Failed ABS sensor"],                                                    fix: "Replace ABS wheel speed sensor.",                                       severity: "moderate",     costRange: "$150-$500" },
  C0045: { description: "Left Rear Wheel Speed Sensor Circuit Malfunction",            causes: ["Failed ABS sensor"],                                                    fix: "Replace ABS wheel speed sensor.",                                       severity: "moderate",     costRange: "$150-$500" },
  C0050: { description: "Right Rear Wheel Speed Sensor Circuit Malfunction",           causes: ["Failed ABS sensor"],                                                    fix: "Replace ABS wheel speed sensor.",                                       severity: "moderate",     costRange: "$150-$500" },
});
